:jbake-title: Dialogs
:jbake-type: section
:jbake-status: published

:source-dir: ../../../../../../vaadin-flow/samples/test-playground/src/main/java

[[dialogs]]
=== Dialogs

NOTE: Dependency <<_linkki_application_framework, `linkki-application-framework`>> is needed.

==== Creating dialogs with PMOs using layout annotation

Dialogs can be created with PMOs annotated with any <<layout, layout annotation>> when using `PmoBasedDialogFactory`.
Instances of `PmoBasedDialogFactory` with a pre-configured `IpsPropertyDispatcherFactory` can be created using
`IpsDialogCreator#create()` or `IpsDialogCreator#with(ValidationService)` methods.

NOTE: PMO classes without any layout annotation are not supported when using `PmoBasedDialogFactory`

.Creating a dialog using `PmoBasedDialogFactory`
[source,java]
----
include::{source-dir}/org/linkki/samples/playground/dialogs/VerticalLayoutContentDialog.java[tags=openDialog]
----

.PMO using `@UIVerticalLayout`
[source,java]
----
include::{source-dir}/org/linkki/samples/playground/dialogs/VerticalLayoutContentDialog.java[tags=verticalLayout]
----

[[uiOpenDialogButton]]
==== Creating dialogs on button click
[NOTE]
Note that this annotation is an experimental feature that may be subject of API change in the near future.

Sometimes, a value or a grid item should not be edited directly.
Instead, a dialog should be opened upon a button click in which the user can edit the value in a more complex form.
To implement this use case, `BindingContext#modelChanged` often needs to be passed to the PMO to update the underlying `BindingContext` after the OK button was clicked.

The UI annotation `@UIOpenDialogButton` resolves this inconvenience.
The annotated method returns a `DialogPmo` that is used to create the dialog that is opened upon button click. For use with a Faktor-IPS model object, the abstract class <<ips-dialog-pmo, `IpsDialogPmo`>> provides a partial implementation of `DialogPmo`.
When the user clicks on the OK button, the underlying `BindingContext` is updated automatically.

.Dialog created with `@UIOpenDialogButton`
[source,java]
----
include::{source-dir}/org/linkki/samples/playground/ts/dialogs/UIOpenDialogButtonPmo.java[tags=uiOpenDialogButton]
----

The annotated method must return a `DialogPmo`, which defines the following properties:

* The caption used to create the dialog.
* The OK handler that is called when pressing the dialogs OK button.
* The PMO for the content of the dialog.
* A validate method that returns a `MessageList` containing validation messages that are shown in the dialog.
By default, no validation is executed.
* The <<property-dispatcher, `PropertyDispatcherFactory`>> that handles the communication between properties and their behaviour.

[NOTE]
The annotation only works with dialogs whose content can be defined as a PMO.

[TIP]
====
* Combine this annotation with <<section-header-annotation,`@SectionHeader`>> to place the button in the header of a section.
* To display an icon instead of a caption, set `caption = ""` or `captionType = CaptionType.NONE` and use <<bind-icon,`@BindIcon`>> to define the icon.
* `DialogPmo` can be used to define dialogs even if `@UIOpenDialogButton` is not used.
====

.Example DialogPmo and ContentPmo
[source,java]
----
include::{source-dir}/org/linkki/samples/playground/ts/dialogs/UIOpenDialogButtonPmo.java[tags=dialogPmo]
----