:jbake-title: Maven Archetypes
:jbake-type: section
:jbake-status: published

:images-folder-name: 01_getting_started

[[maven-archetypes]]
=== Maven Archetypes

linkki can be used for a <<maven-archetypes-plain, plain Vaadin web application>> or with <<maven-archetypes-spring, Spring Boot>>.
For each of those options, there is a matching Maven archetype that creates a new project with all necessary dependencies and some sample code to get started.
They can be created from a command line.

[[maven-archetypes-plain]]
==== Plain linkki

[source,subs="verbatim,attributes"]
.Command to execute the archetype
----
mvn archetype:generate -DarchetypeGroupId=org.linkki-framework.archetypes -DarchetypeArtifactId=linkki-archetype-plain-application-vaadin-flow -DarchetypeVersion={projectVersion}
----

The resulting application can be deployed to your application server of choice or simply started with `mvn clean package org.eclipse.jetty:jetty-maven-plugin:run`, where it can be viewed at `http://localhost:8080/`.

[[maven-archetypes-spring]]
==== linkki with Spring Boot

[source,subs="verbatim,attributes"]
.Command to execute the archetype
----
mvn archetype:generate -DarchetypeGroupId=org.linkki-framework.archetypes -DarchetypeArtifactId=linkki-archetype-spring-application-vaadin-flow -DarchetypeVersion={projectVersion}
----

For the seamless operation of applications built using the Spring Archetype, adherence to the proper startup procedures is recommended:

Development mode:: After packaging, use `mvn spring-boot:run` to start the application.
+
[source,go]
.Example
----
mvn package
mvn spring-boot:run
----

The application can then be viewed at `http://localhost:8080/`

=== Initial project structure

Both archetypes produce the same basic project structure, differing only in the class used to start the application.
The following overview uses `Demo` as the example application name.

[cols="1,1", frame=none, grid=none]
|===
a|.Plain archetype
....
demo-plain/
└── src/main/
    ├── java/
    │   ├── DemoAppShellConfigurator.java
    │   ├── ui/
    │   │   ├── DemoApplicationConfig.java
    │   │   ├── DemoApplicationInfo.java
    │   │   └── DemoApplicationLayout.java
    │   └── view/
    │       ├── DemoPage.java
    │       ├── DemoView.java
    │       └── HelloPmo.java
    └── resources/
        └── simplelogger.properties
....
a|.Spring archetype
....
demo-spring/
└── src/main/
    ├── java/
    │   ├── DemoApplication.java
    │   ├── ui/
    │   │   ├── DemoApplicationConfig.java
    │   │   ├── DemoApplicationInfo.java
    │   │   └── DemoApplicationLayout.java
    │   └── view/
    │       ├── DemoPage.java
    │       ├── DemoView.java
    │       └── HelloPmo.java
    └── resources/
        └── application.properties
....
|===

`DemoApplicationInfo`:: Defines basic information about the *linkki* application such as name, version, description, and copyright.

`DemoApplicationConfig`:: Implements `ApplicationConfig` to provide the `DemoApplicationInfo` and the application menu items.

`DemoApplicationLayout`:: Extends `ApplicationLayout` and uses `DemoApplicationConfig` to set up the overall page layout including header and footer.

`HelloPmo`:: A PMO (Presentation Model Object) that defines a section with a text field, a label, and a button.
Annotations like `@UITextField` are used to declare UI elements.
For more information see <<ui-element, UI elements>>.

`DemoPage`:: Extends `AbstractPage` and defines the page content by adding sections from PMOs such as `HelloPmo`.

`DemoView`:: Defines the entrypoint of the main page.