:jbake-title: Getting Started
:jbake-type: chapter
:jbake-status: published
:jbake-order: 1

:sample-parent-dir: ../../../../../../vaadin-flow/samples
:source-dir: ../../../../src/main/java
:images-folder-name: 01_getting_started

[[getting-started]]
== Getting Started

You can either add the required dependencies to an existing project or use one of the <<maven-archetypes,Maven archetypes>> to get started.

=== Maven dependencies

==== linkki-bom

The linkki BOM in `linkki-bom` groups all dependency versions that are known to be valid and tested to work together for linkki projects.
This will reduce the developers’ pain of having to test the compatibility of different versions and reduce the chances to have version mismatches.

To create a *linkki* project, just add this linkki BOM and any of the following dependencies depending on the feature set you need.
 
[source,xml]
----
include::{sample-parent-dir}/pom.xml[tags=linkki-bom]
----

==== linkki-core

[source,xml]
----
include::{sample-parent-dir}/getting-started/pom.xml[tags=linkki-core]
----

==== linkki-vaadin-flow-component

`linkki-vaadin-flow-component` contains the following additional features:

* <<linkkitablayout, Sidebar layout>>

[source,xml]
----
include::{sample-parent-dir}/test-playground/pom.xml[tags=linkki-vaadin-flow-component]
----

==== linkki-application-framework

`linkki-application-framework` contains the following additional features:

* <<dialogs, Dialogs>>
* `LinkkiUi` with `ApplicationLayout` and `ApplicationConfig` as well as an adjusted theme
* UI Components to display validation messages

[source,xml]
----
include::{sample-parent-dir}/test-playground/pom.xml[tags=linkki-application-framework]
----

[[linkki-search-dependency]]
==== linkki-search-vaadin-flow

`linkki-search-vaadin-flow` contains the following additional features:

* <<linkki-search, Search components>>

[source,xml]
----
include::{sample-parent-dir}/test-playground/pom.xml[tags=linkki-search-vaadin-flow]
----

==== linkki-ips-vaadin-flow

`linkki-ips-vaadin-flow` contains the following additional features:

* <<fips-extension, Faktor-IPS extension>>

[source,xml]
----
include::{sample-parent-dir}/test-playground/pom.xml[tags=linkki-ips-vaadin-flow]
----

In addition to the *linkki* dependency, a *linkki* application with Vaadin may require a Vaadin Spring Boot starter.