:jbake-type: referenced
:jbake-status: referenced
:jbake-order: 0

// NO :source-dir: HERE, BECAUSE N&N NEEDS TO SHOW CODE AT IT'S TIME OF ORIGIN, NOT LINK TO CURRENT CODE
:images-folder-name: 01_releasenotes

=== Version 2.5.0

==== New features and improvements

===== Version Updates
.Updated dependency versions:
[cols="a,a"]
|=== 
|Faktor-IPS|23.6.2.release
|===

//https://jira.convista.com/browse/LIN-3144
//https://jira.convista.com/browse/LIN-3067
[role="api-change"]
===== Improved update behavior

The update behavior has been improved for two cases:

Invisible PMOs:: Updates of child bindings are now skipped entirely if the PMO is invisible. This reduces the number of unnecessary binding updates, making using nested components more efficient.

Null model object:: When using model binding, linkki would throw an exception if the model object is `null` upon creation or update until now. With this change, linkki would gracefully handle the `null` value.
+
How the `null` value is handled depends on the respective aspect definition.
Aspect definitions that are provided by linkki are adjusted accordingly. In case of the value aspect, the field value is cleared if the model object is `null`. Boolean valued aspects such as enabled or visible are set to `false`.
+
Custom aspect definition may need to be adjusted to be able to handle `null` value. If model object is `null` upon update, `PropertyDispatcher#pull` now returns `null` instead of throwing an exception. This can then be handled in the UI updater created in `LinkkiApsectDefinition#createUiupdater`.
+
When using `ModelToUiAspectDefinition`, a new method `#handleNullItem` has been introduced which can be overridden to define the `null` handling. The behavior defaults to calling the component value setter created by `#createComponentValueSetter` with `null`.


// https://jira.convista.com/browse/LIN-3470
[role="api-change"]
===== Additional utility for Karibu testing
`KaribuUIExtension`::
To use `KaribuUIExtension` a test class can either be annotated with `@ExtendWith(KaribuUIExtension.class)` or registered via `@RegisterExtension`. The latter allows e.g. to register and use custom classes as routes in Vaadin UI tests. Additionally, a test using `KaribuUIExtension` can be annotated with `@WithLocale` to define the UI's locale, defaulting to german.

`KaribuUtils`::
Provides utility methods for handling `Notification`-components.

NOTE: `VaadinUIExtension` has been deprecated since `KaribuUIExtension` not only offers the same functionality, but also additional features.

// ===== Other

==== Bugfixes
// https://jira.faktorzehn.de/browse/LIN-3513
* Fixed wrong min-width in @UISection for layouts where the label is above the component
// https://jira.convista.com/browse/LIN-3483
* Fixed the issue where multiple screenshots taken for a single test case would overwrite each other
