:jbake-type: referenced
:jbake-status: referenced
:jbake-order: 0

// NO :source-dir: HERE, BECAUSE N&N NEEDS TO SHOW CODE AT IT'S TIME OF ORIGIN, NOT LINK TO CURRENT CODE
:images-folder-name: 01_releasenotes

=== Version 2.5.0

==== New features and improvements

===== Version Updates
.Updated dependency versions:
[cols="a,a"]
|=== 
|Faktor-IPS         |24.1.0.a20230828-01
|Vaadin             |24.1.7
|===

// https://jira.convista.com/browse/LIN-3144
// https://jira.convista.com/browse/LIN-3067
// https://jira.convista.com/browse/LIN-3551
[role="api-change"]
===== Improved update behavior

The update behavior has been improved for two cases:

Invisible PMOs:: Updates of child bindings are now skipped entirely if the PMO is invisible. This reduces the number of unnecessary binding updates, making using nested components more efficient.

Null model object:: When using model binding, linkki would throw an exception if the model object is `null` upon creation or update until now. With this change, linkki would gracefully handle the `null` value.
+
How the `null` value is handled depends on the respective aspect definition.
Aspect definitions that are provided by linkki are adjusted accordingly. In case of the value aspect, the field value is cleared if the model object is `null`. Boolean valued aspects such as enabled or visible are set to `false`.
+
Custom aspect definition may need to be adjusted to be able to handle `null` value. If model object is `null` upon update, `PropertyDispatcher#pull` now returns `null` instead of throwing an exception. This can then be handled in the UI updater created in `LinkkiApsectDefinition#createUiupdater`.
+
When using `ModelToUiAspectDefinition`, a new method `#handleNullItem` has been introduced which can be overridden to define the `null` handling. The behavior defaults to calling the component value setter created by `#createComponentValueSetter` with `null`.
+
To be able to handle `null` values for generic model objects properly when using the `PropertyDispatcherFactory`, `MemberAccessors#getType(Member)` has been deprecated and replaced by `MemberAccessors#getType(Member, Type)`, where `Type` is the concrete PMO class.


// https://jira.convista.com/browse/LIN-3470
[role="api-change"]
===== Additional utility for Karibu testing
`KaribuUIExtension`::
To use `KaribuUIExtension` a test class can either be annotated with `@ExtendWith(KaribuUIExtension.class)` or registered via `@RegisterExtension`. The latter allows e.g. to register and use custom classes as routes in Vaadin UI tests. Additionally, a test using `KaribuUIExtension` can be annotated with `@WithLocale` to define the UI's locale, defaulting to german.

`KaribuUtils`::
Provides utility methods for handling `Notification`-components.

NOTE: `VaadinUIExtension` has been deprecated since `KaribuUIExtension` not only offers the same functionality, but also additional features.

// https://jira.convista.com/browse/LIN-3406
[role="api-change"]
===== Member access utility methods cleaned up for public access

Classes such as `PropertyAccessor` or `MemberAccessors` are useful classes that can be used for aspect definitions, or when writing a custom UI annotation. `MemberAccessors` offer methods to read field and method values, while `PropertyAccessor` and find and read the value of a property using the getter method, as well as call the corresponding call or invoke method.

Up until now, these classes are intended for internal usage. With this version, they are moved to the `linkki-utils` module to make them more accessible. Associated classes that should remain being used internally are made package private:

* `ReadMethod`
* `WriteMethod`
* `InvokeMethod`
* `PropertyAccessorDescriptor`
* `PropertyAccessorCache`

`PropertyAccessorCache#get` can be replaced with `PropertyAccessor#get`. All other usages of the internal classes should be removed.

// https://jira.convista.com/browse/LIN-1767
===== Removed generated Vaadin files
Files generated by Vaadin can now be removed from the repository without affecting the speed of the build.
The advantage of this is that a Vaadin version update does not cause any further Git differences.

It is not required to list these files in `.gitignore` since they are automatically deleted by the Vaadin build if they did not exist before.

Affected files, for example:

* `package.json`
* `package-lock.json`
* `tsconfig.json`
* `typed.d.ts`
* `vite.config.ts`

// https://jira.convista.com/browse/LIN-1621
[role="api-change"]
===== Partial support for `null` model objects in `IpsPropertyDispatcher`
When determining a label from the Faktor-IPS model, the `IpsPropertyDispatcher` now falls back to the declared model object class if the model object of a PMO is `null`.
This behavior is only supported for labels.

Therefore, the constructor `IpsPropertyDispatcher(Supplier, Supplier, String, PropertyDispatcher)` has been added. The second supplier can be used to provide the model object class used for the fallback.
The constructor `IpsPropertyDispatcher(Supplier, String, PropertyDispatcher)` has been deprecated.

//https://jira.convista.com/browse/LIN-1921
===== Overloaded Constructors for `DialogBindingManager` and `PmoBaseDialogFactory`
The DialogBindingManager class has been enhanced to offer an overloaded constructor, which now accommodates an extra parameter of type PropertyDispatcherFactory. This enhancement provides flexibility by allowing the use of a custom PropertyDispatcherFactory, or falling back to the default Java constructor for PropertyDispatcherFactory.

Similarly, the PmoBasedDialogFactory class has also been equipped with an overloaded constructor that embraces the PropertyDispatcherFactory parameter, or reverting to the default Java constructor if needed. Additionally, the PmoBasedDialogFactory class has been seamlessly integrated with the recently introduced overloaded constructor of the DialogBindingManager class.


// https://jira.convista.com/browse/LIN-550
[role="api-change"]
===== `UITimeField` added

A new annotation <<ui-timefield, @UITimeField>> has been added for selecting a time. 
The annotation has the property `step` for setting the time interval in the time picker overlay.


===== Improved Styling and Consistency for linkki Theme
Following table defines a mapping between linkki and Lumo color definitions. For each linkki color, the corresponding Lumo color is identified. It's important to note that some linkki colors, such as --linkki-info-text-color, do not have a direct Lumo counterpart, marked as "N/A" in the table.

|===
|linkki Color |Lumo Color

|--linkki-info-color
|N/A (custom color used)

|--linkki-info-text-color
|N/A (custom color used)

|--linkki-warning-color
|--lumo-warning-color

|--linkki-warning-text-color
|--lumo-warning-text-color

|---linkki-success-color
|--lumo-success-color

|--linkki-success-text-color
|--lumo-success-text-color

|--linkki-warning-text-color
|--lumo-warning-text-color

|--linkki-warning-text-color
|--lumo-warning-text-color
|===

The table below defines visual behaviors for icons and text based on their specific classes. These styles primarily target the `vaadin-icon` component within linkki, enabling a more dynamic visual feedback system.

|===
|CSS Selector |Color Variable Used

|icon-success > vaadin-icon
|--linkki-success-color

|icon-warning > vaadin-icon
|--linkki-warning-color

|icon-error > vaadin-icon
|--linkki-error-color

|icon-info > vaadin-icon.linkki-text-icon
|--linkki-info-color

|text-info
|--linkki-info-text-color

|linkki-text.text-success > span
|--lumo-success-text-color

|linkki-text.text-warning > span
|--lumo-warning-text-color

|linkki-text.text-error > span
|--lumo-error-text-color

|linkki-text.text-info > span
|--linkki-info-text-color
|===

There are a few selectors that have been deprecated in favor of new ones that are more consistent with linkki and Lumo.

|===
|Deprecated Selector |New Selector

|LinkkiTheme#PLACEHOLDER_LABEL
|LinkkiTheme.Text#TEXT_PLACEHOLDER

|LinkkiApplicationTheme#TEXT_RIGHT_ALIGNED
|LumoUtility.TextAlign#RIGHT

|LinkkiApplicationTheme#MESSAGE_PREFIX
|MessageUiComponents#ICON_STYLE_CLASS_PREFIX
|===

===== Other
// https://jira.convista.com/browse/LIN-3557
* The <<maven-archetypes-spring, documentation>> that describes how to build and start an application created by the Spring Boot archetype has been adjusted to match the different requirements regarding development and production mode. 

==== Bugfixes
// https://jira.faktorzehn.de/browse/LIN-3513
* Fixed wrong min-width in @UISection for layouts where the label is above the component
// https://jira.convista.com/browse/LIN-3483
* Fixed the issue where multiple screenshots taken for a single test case would overwrite each other
// https://jira.convista.com/browse/LIN-3507
* Fixed added child rows are not visible in hierarchical tables
// https://jira.convista.com/browse/LIN-3422
* Fixed the issue where error messages in a HorizontalLayout containing nested components within a Section were causing misalignment due to the VerticalLayout being set to "Middle." The fix involved setting the vertical alignment of UIHorizontalLayout to "Baseline," ensuring consistent alignment and enhancing visual cohesiveness and readability.
// https://jira.convista.com/browse/LIN-3531
* Fixed @BindMessages not working on Grid column fields
// https://jira.convista.com/browse/LIN-3530
* Fixed empty rows in MessageTablePmo when duplicate messages are present
// https://jira.convista.com/browse/LIN-3588
* Missing English resource bundle has been added for `DatePickerI18nCreator`, which is used to internationalize a `DatePicker`