:jbake-type: referenced
:jbake-status: referenced
:jbake-order: 0

// NO :source-dir: HERE, BECAUSE N&N NEEDS TO SHOW CODE AT IT'S TIME OF ORIGIN, NOT LINK TO CURRENT CODE
:images-folder-name: 01_releasenotes

=== Version 2.4.0

This release brings a new technology baseline that includes Java 17, Spring Boot 3, Jakarta EE 10, Vaadin 24 and Faktor-IPS 23.6. These upgrades not only make it possible for linkki developers to make use of the new features of these platforms, it also ensures that the linkki application relies on the latest technologies that are well supported in the near future.

Java 17:: Java 17 is required instead of Java 11. This primarily impacts the build environment, as well as the Java version definition in the `pom.xml`.

Artifact Names:: Due to the upgrade to Vaadin 24, all artifacts have been renamed to use `vaadin-flow` instead of `vaadin23`. This includes following dependencies: +
* `linkki-core-vaadin23`, now `linkki-core-vaadin-flow`
* `linkki-core-nestedcomponent-vaadin23`, now `linkki-core-nestedcomponent-vaadin`
* `linkki-application-framework-vaadin23`, now `linkki-application-framework-vaadlin-flow`
* `linkki-ips-vaadin23`, now `linkki-ips-vaadin-flow`

Vaadin 24:: Vaadin 24 brings several breaking changes that are documented in the https://vaadin.com/docs/latest/upgrading#breaking-changes-in-vaadin-components[Vaadin migration guide]. 
+
* The breaking API changes only have an effect on code that uses Vaadin API directly. There are no resulting linkki API changes. To see all breaking API changes, see https://github.com/vaadin/flow-components/releases/tag/24.0.0[Vaadin release notes for Flow Components].
** `Label` component was deprecated as it is often misused to display text content. This may lead to unexpected behavior in the UI. Check all usages if they should be replaced by a `Span` instead. `Label` is replaced by `NativeLabel` which still can be used if a `<label>` element is necessary.
* Fields from `LumoUtility` are no longer constant expressions, meaning they can no longer be used in annotations, e.g. `@BindStyleNames({ LumoUtility.Flex.AUTO })`. linkki now provides the class `LumoConstants`, that defines the same fields as constant expressions, to mitigate this problem. All existing usages of constants from `LumoUtility` in annotations should be replaced by `LumoConstants`.
* The way frontend resources are included has changed. Consequently, CSS and JavaScript files that are included by using `@CSSImport` or `@JsModule` may not be included anymore, if the class on which the files are included are only reachable by reflection or injection. If this problem occurs, an error can be found in the console when the affected page is opened in the browser. To mitigate this issue, add `@Uses` to the according route component with the class where the resources are included, or to a class that can be reached from the route.
* There are some changes in the resulting DOM structure that may impact UI tests and CSS selectors.
+
--
** Some components are now in the light DOM instead of being in the shadow DOM, e.g.:
*** Buttons in `MenuBar`
*** Elements in `DatePicker`
*** Elements in `Upload`
*** Elements in `MultiSelectComboBox`
+
** Some CSS properties have changed, e.g.:
*** `--lumo-border-radius` is removed. Use `--lumo-border-radius-m` instead.
*** CSS properties to set the border radius of input fields have changed. `--vaadin-input-container-top-end-radius` is now `--vaadin-input-field-top-end-radius`, `--vaadin-input-container-bottom-end-raiuds` is now `--vaadin-input-field-bottom-end-radius`
--
For all frontend changes, see https://github.com/vaadin/web-components/releases/tag/v24.0.0[Vaadin release notes for Vaadin Web Components].
* Visually, the application looks mostly the same as with Vaadin 23. Following visual changes may need styling adjustments if the previous behavior need to be restored:
+
--
** The `Accordion` component now display the closable toggle button directly after the caption instead of on the right end of the caption.
** All Headings (`h1` - `h6`) do not have a default margin anymore. Components in linkki do not have to be adjusted. If headings are used in any other components, check visually if the margin still behave as expected.
--
Styling changes can also be found in https://github.com/vaadin/web-components/releases/tag/v24.0.0[Vaadin release notes for Vaadin Web Components].
* The `snakeyaml` dependency, which is required for using YAML configuration files with Spring Boot, has been excluded by Vaadin in this version. To continue using YAML files, following dependency must manually be added:
+
[source,xml]
----
<dependency>
    <groupId>org.yaml</groupId>
    <artifactId>snakeyaml</artifactId>
</dependency>
---- 
* When using Karibu for unit testing, the version has to be updated to 2.0.0 or greater:
+
[source,xml]
----
<dependency>
    <groupId>com.github.mvysny.kaributesting</groupId>
    <artifactId>karibu-testing-v24</artifactId>
    <version>2.0.2</version>
    <scope>test</scope>
</dependency>
----

Faktor-IPS 23.6:: The <<fips-extension, linkki Faktor-IPS extension>> uses the latest Faktor-IPS version 23.6. There are no resulting API changes in the Faktor-IPS extension.

Spring Boot 3 and Jakarta EE 10:: Spring-based applications need to upgrade to Spring Boot 3 or Spring framework 6. Spring Boot 2 is no longer supported by Vaadin. The <<maven-archetypes, Spring Boot archetype>> has been upgraded to Spring Boot 3 accordingly. +
Non-Spring application needs to be upgraded to be compatible with Jakarta EE 10.

==== New features and improvements

===== Improvements in Testbench-Extension

The `WebDriverExtension` has been extended with an additional constructor that can be used by just passing the context path. In that case, the fully qualified URL is built based on the given path together with the defined test driver properties. This prevents that the fully qualified URL always has to be handed over as a whole.
The defined test driver system properties can be accessed by `DriverProperties`.

[role="api-change"]
===== Hide exception stacktraces in production mode and customize the error dialog
////
https://jira.faktorzehn.de/browse/LIN-2729
////
For security reasons, exception stacktraces are not shown in the default error dialog anymore when the application runs in production mode.

To make this behavior and error handling in whole more configurable, following API changes has been made:

.API changes
[cols="a,a"]
|=== 
| Changes | Description
| `AplicationLayout#getErrorHandler()` a| This method has been deleted as the application layout is not always easily customizable. The method is moved to `AplicationConfig#getErrorHandler()`.
| `DefaultErrorDialog` a| Deprecated.  This class is not used by default anymore.
| `DialogErrorHandler(BiFunction)` a| Deprecated. Use `DialogErrorHandler(ErrorDialogConfiguration)` instead or implement an own `ErrorHandler` to use a custom error dialog.
| `DialogErrorHandler(BiFunction, String)` a| Deprecated. Use `DialogErrorHandler(ErrorDialogConfiguration)` instead or implement an own `ErrorHandler` to use a custom error dialog.
|===

About how to customize error handling, see <<error-handler, documentation>>.

===== Vaadin & Spring update
////
https://jira.faktorzehn.de/browse/LIN-3319
////
Vaadin has been updated to version 24.1.0 Spring Boot to version 3.1.0.
[WARNING]
==== 
The `snakeyaml` dependency, which is required for using YAML configuration files with Spring Boot, has been excluded by Vaadin. To continue using YAML files, following dependency must manually be added:
[source,xml]
----
<dependency>
    <groupId>org.yaml</groupId>
    <artifactId>snakeyaml</artifactId>
</dependency>
----
====


[role="api-change"]
===== Improved detection for internationalized Strings

////
https://jira.faktorzehn.de/browse/LIN-967
////
Internationalized Strings from super classes and interfaces::
In previous versions, internationalized Strings from super classes and interfaces had to be copied to the properties file of the subclass, with the key adjusted to the subclass. This made the internationalization process complicated. With this change, the internationalized Strings from super classes and interfaces are now automatically taken into account by linkki. As a result, only the String aspects that are new in the subclass need to be defined in the properties file. The new mechanism for the detection of internationalized Strings are described in the <<nls-properties,documentation>>.

Simplified key pattern for keys without property name::
In case of class level aspect such as placeholder or caption, the key used to be `PmoClassName\__aspectName` as the property name is empty. An exception was made for section captions to make it possible to define `PmoClassName_caption`. This disparity is now resolved in this version. All keys without property name can now be defined with the pattern `PmoClassName_aspectName`, which omits the second underscore for convenience. The regular pattern `PmoClassName__aspectName` remains functional and has a higher precedence over the key with only one underscore.

.In this example, the section caption would be `myNewCaption`
[source,properties]
----
MyClass__caption=myNewCaption
MyClass_caption=myOldCaption
----

.API changes
To accommodate these changes, some internal API changes have been made:
[cols="a,a"]
|===
| Changes | Description
| `PmoNlsService` a| Deprecated. Use `StaticValueNlsService` instead.
| `PmoBundleNameGenerator` a| Deprecated. The class is being deprecated because it is no longer in use.

|===

===== Other
// https://jira.convista.com/browse/LIN-3360
* The class `org.linkki.util.Optionals` has been deprecated, the `Optional` class from the JDK now offers corresponding functionality. The replacement methods are linked in the JavaDoc.
// https://jira.convista.com/browse/LIN-3219
* Excluded the dependency `com.google.code.findbugs:jsr305` from the compile scoped dependencies of the module `linkki-core-vaadin-flow` 


==== Bugfixes

// https://jira.faktorzehn.de/browse/LIN-3319
===== Sanitization of HTML content

Using `@UILabel` with `htmlContent = true` previously did not sanitize the content. To make the behaviour of `htmlContent = true` more secure by default, the HTML is now automatically sanitized, removing potentially dangerous tags and attributes. Note that the tags `img` and `vaadin-icon` are also whitelisted.

The same applies to `org.linkki.core.vaadin.component.base.LinkkiText` when using HTML content mode (`setText(..., true)`).

[WARNING]
==== 
When user-supplied strings are included in HTML content, they have to be escaped to prevent them from being interpreted as HTML. This can be achieved by using `HtmlSanitizer#escapeText`.
====

// https://jira.faktorzehn.de/browse/LIN-3415
* Fixed overlapping labels and input fields in small browser windows

===== Other
// https://jira.faktorzehn.de/browse/LIN-3384
* Fixed an incompatibility with ChromeDriver versions 111 and above in `linkki-vaadin-flow-testbench-extension`
// https://jira.convista.com/browse/LIN-3362
* Deprecated unused method `HierarchicalRowPmo#hasChildRows`
// https://jira.faktorzehn.de/browse/LIN-3313
* Fixed unnecessary horizontal scroll bar in ComboBox overlay
// https://jira.faktorzehn.de/browse/LIN-3403
* Fixed wrong timestamp format in error dialogs
// https://jira.faktorzehn.de/browse/LIN-3437
* Fixed falsely marked as invalid combobox with initial non-null but empty representation
