:jbake-type: referenced
:jbake-status: referenced
:jbake-order: 0

// NO :source-dir: HERE, BECAUSE N&N NEEDS TO SHOW CODE AT IT'S TIME OF ORIGIN, NOT LINK TO CURRENT CODE
:images-folder-name: 01_releasenotes

=== Version 2.4.0

==== New features and improvements

===== Enhance Testbench-Extension
The `WebDriverExtension` has been extended with an additional constructor that can be used by just passing the context path. In that case, the fully qualified URL is built based on the given path together with the defined test driver properties. This prevents that the fully qualified URL always has to be handed over as a whole.
The defined test driver system properties can be accessed by `DriverProperties`.

[role="api-change"]
===== Hide exception stacktraces in production mode and customize the error dialog
////
https://jira.faktorzehn.de/browse/LIN-2729
////
For security reasons, exception stacktraces are not shown in the default error dialog anymore when the application runs in production mode.

To make this behavior and error handling in whole more configurable, following API changes has been made:

.API changes
[cols="a,a"]
|=== 
| Changes | Description
| `AplicationLayout#getErrorHandler()` a| This method has been deleted as the application layout is not always easily customizable. The method is moved to `AplicationConfig#getErrorHandler()`.
| `DefaultErrorDialog` a| Deprecated.  This class is not used by default anymore.
| `DialogErrorHandler(BiFunction)` a| Deprecated. Use `DialogErrorHandler(ErrorDialogConfiguration)` instead or implement an own `ErrorHandler` to use a custom error dialog.
| `DialogErrorHandler(BiFunction, String)` a| Deprecated. Use `DialogErrorHandler(ErrorDialogConfiguration)` instead or implement an own `ErrorHandler` to use a custom error dialog.
|===

About how to customize error handling, see <<error-handler, documentation>>.

===== Vaadin & Spring update
////
https://jira.faktorzehn.de/browse/LIN-3319
////
Vaadin has been updated to version 23.3.5 and Spring Boot to version 2.7.8.
[WARNING]
==== 
The `snakeyaml` dependency, which is required for using YAML configuration files with Spring Boot, has been excluded by Vaadin. To continue using YAML files, following dependency must manually be added:
[source,xml]
----
<dependency>
    <groupId>org.yaml</groupId>
    <artifactId>snakeyaml</artifactId>
</dependency>
----
====


==== Bugfixes

// https://jira.faktorzehn.de/browse/LIN-3319
===== Sanitization of HTML content

Using `@UILabel` with `htmlContent = true` previously did not sanitize the content. To make the behaviour of `htmlContent = true` more secure by default, the HTML is now automatically sanitized, removing potentially dangerous tags and attributes. Note that the tags `img` and `vaadin-icon` are also whitelisted.

The same applies to `org.linkki.core.vaadin.component.base.LinkkiText` when using HTML content mode (`setText(..., true)`).

[WARNING]
==== 
When user-supplied strings are included in HTML content, they have to be escaped to prevent them from being interpreted as HTML. This can be achieved by using `HtmlSanitizer#escapeText`.
====

===== Other
// https://jira.faktorzehn.de/browse/LIN-3384
* Fixed an incompatibility with ChromeDriver versions 111 and above in `linkki-vaadin23-testbench-extension`
// https://jira.convista.com/browse/LIN-3362
* Deprecated unused method `HierarchicalRowPmo#hasChildRows`