:jbake-type: referenced
:jbake-status: referenced
:jbake-order: 0

// NO :source-dir: HERE, BECAUSE N&N NEEDS TO SHOW CODE AT IT'S TIME OF ORIGIN, NOT LINK TO CURRENT CODE
:images-folder-name: 01_releasenotes

=== Version 2.3.0

==== New features and improvements

===== `@BindMessages`
////
https://jira.faktorzehn.de/browse/LIN-1090
////
A new annotation, `@BindMessages`, has been added for manually filtering and setting validation messages on a field.

For more information see "<<bind-messages, @BindMessages>>".

[role="api-change"]
===== `Refactoring BindingDescriptor`
////
https://jira.faktorzehn.de/browse/LIN-1090
////
The class `BindingDescriptor` has been completely refactored and should now be used directly instead of creating a child class.

As part of this process, the following classes and methods were deleted:

* `ElementDescriptor` - use `BindingDescriptor` instead
* `PropertyElementDescriptors ` - use `BindingDescriptor` instead
* `public BindingDescriptor(List<LinkkiAspectDefinition>)` - use `public BindingDescriptor(BoundProperty, List<LinkkiAspectDefinition>)` instead

And the following elements were deprecated:

* `BindingDescriptor.getModelAttributeName()` - call `BindingDescriptor.getBoundProperty().getModelAttribute()` instead
* `BindingDescriptor.getModelObjectName()` - call `BindingDescriptor.getBoundProperty().getModelObjectName()` instead
* `BindingDescriptor.getPmoPropertyName()` - call `BindingDescriptor.getBoundProperty().getPmoPropertyName()` instead
* `LinkkiBoundProperty.ModelObject` - use `LinkkiBoundProperty.ModelObjectProperty` instead

===== `@BindAutoFocus`
////
https://jira.faktorzehn.de/browse/LIN-1845
////
A new annotation, `@BindAutoFocus`, has been added for setting the https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus[autofocus] attribute on a UI element.

Please note that this annotation should not be used on more than one UI element per page/dialog, and that the target element has to be visible and editable.

For more information see "<<autofocus, @BindAutoFocus>>".

===== `@BindVariantNames`
////
https://jira.faktorzehn.de/browse/LIN-2709
////


A new annotation `@BindVariantNames` has been added for adding Vaadin variants to UI elements or PMO classes.

For more information see "<<variant-names, @BindVariantNames>>".

===== `@BindLabel`
////
https://jira.faktorzehn.de/browse/LIN-2529
////


A new annotation `@BindLabel` has been implemented for adding dynamic labels to UI elements.

For more information see "<<bind-label, @BindLabel>>".

===== `@UIMultiSelect`
////
https://jira.faktorzehn.de/browse/LIN-3201
////

A new UI element annotation `@UIMultiSelect` has been added for selecting multiple elements from a list of allowed values.

For more information see "<<ui-multiselect, @UIMultiSelect>>".


===== `null` behaviour in `@UIRadioButtons`
////
https://jira.faktorzehn.de/browse/LIN-3213
////
Fixed `@UIRadioButtons` not showing null when using `AvailableValuesType.ENUM_VALUES_INCL_NULL`.

IMPORTANT: Please check the method `String getNullCaption()` of all `ItemCaptionProviders` that are used with `@UIRadioButtons` and make sure that this method returns the string for the `null` value. `getCaption()` will not be called for a `null` value!

===== `iconPosition` for `@UILabel` and `@UILink`

A new property `iconPosition` has been added to both `<<ui-label, @UILabel>>` and `<<ui-link, @UILink>>` for positioning the icon to the left or right of the label/link.
The default position is left for `@UILabel` and right for `@UILink`.

==== Bugfixes

// https://jira.faktorzehn.de/browse/LIN-3220
* Fix warning and info notifications not being closeable when the respective duration is set to 0 or below. The notifications will now have a close button, like error notifications. _(since 2.1.3)_
// https://jira.faktorzehn.de/browse/LIN-3221
* Fields for which Vaadin does not support validation (components not implementing `HasValidation`, e.g. buttons) now have the HTML attributes `invalid` and `severity` set by linkki to allow custom styling via CSS. The message text is not displayed. _(since 2.1.3)_
// https://jira.faktorzehn.de/browse/LIN-3176
* Fix icon size for `LinkkiText` and `LinkkiAnchor` _(since 2.1.2)_
// https://jira.faktorzehn.de/browse/LIN-3150
* `IpsPropertyDispatcher` now handles empty value sets correctly _(since 2.1.1)_
// https://jira.faktorzehn.de/browse/LIN-3159
* Fix disabled state of checkboxes _(since 2.1.1)_
// https://jira.faktorzehn.de/browse/LIN-3149
* `LinkkiTabLayout` no longer initializes content of tabs when removing them _(since 2.1.1)_
// https://jira.faktorzehn.de/browse/LIN-3153
* `BindingContext#modelChanged` was called when creating a table. This accidentally triggered a `modelChangeHandler` when setting up the UI. _(since 2.1.1)_
// https://jira.faktorzehn.de/browse/LIN-3171
* Fix `@UILink` and `@UILabel` with icons in combination with custom style names added by `@BindStyleNames`. Style class `linkki-has-icon` is not used anymore and will be removed in later version. _(since 2.1.1)_
