:jbake-type: referenced
:jbake-status: referenced
:jbake-order: 0

// NO :source-dir: HERE, BECAUSE N&N NEEDS TO SHOW CODE AT IT'S TIME OF ORIGIN, NOT LINK TO CURRENT CODE
:images-folder-name: 01_releasenotes

=== Version 2.3.0

==== New features and improvements

===== `@BindAutoFocus`
////
https://jira.faktorzehn.de/browse/LIN-1845
////
A new annotation, `@BindAutoFocus`, has been added for setting the https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus[autofocus] attribute on a UI element.

Please note that this annotation should not be used on more than one UI element per page/dialog, and that the target element has to be visible and editable.

For more information, see "<<autofocus, @BindAutoFocus>>".

===== `@BindVariantNames`
////
https://jira.faktorzehn.de/browse/LIN-2709
////

A new annotation, <<variant-names,`@BindVariantNames`>>, has been added for adding Vaadin variants to UI elements or PMO classes.


===== `null` behaviour in `@UIRadioButtons`
////
https://jira.faktorzehn.de/browse/LIN-3213
////
Fixed `@UIRadioButtons` not showing null when using `AvailableValuesType.ENUM_VALUES_INCL_NULL`.

IMPORTANT: Please check the method `String getNullCaption()` of all `ItemCaptionProviders` that are used with `@UIRadioButtons` and make sure that this method returns the string for the `null` value. `getCaption()` will not be called for a `null` value!

==== Bugfixes

// https://jira.faktorzehn.de/browse/LIN-3220
* Fix warning and info notifications not being closeable when the respective duration is set to 0 or below. The notifications will now have a close button, like error notifications. _(since 2.1.3)_
// https://jira.faktorzehn.de/browse/LIN-3221
* Fields for which Vaadin does not support validation (components not implementing `HasValidation`, e.g. buttons) now have the HTML attributes `invalid` and `severity` set by linkki to allow custom styling via CSS. The message text is not displayed. _(since 2.1.3)_
// https://jira.faktorzehn.de/browse/LIN-3176
* Fix icon size for `LinkkiText` and `LinkkiAnchor` _(since 2.1.2)_
// https://jira.faktorzehn.de/browse/LIN-3150
* `IpsPropertyDispatcher` now handles empty value sets correctly _(since 2.1.1)_
// https://jira.faktorzehn.de/browse/LIN-3159
* Fix disabled state of checkboxes _(since 2.1.1)_
// https://jira.faktorzehn.de/browse/LIN-3149
* `LinkkiTabLayout` no longer initializes content of tabs when removing them _(since 2.1.1)_
// https://jira.faktorzehn.de/browse/LIN-3153
* `BindingContext#modelChanged` was called when creating a table. This accidentally triggered a `modelChangeHandler` when setting up the UI. _(since 2.1.1)_
// https://jira.faktorzehn.de/browse/LIN-3171
* Fix `@UILink` and `@UILabel` with icons in combination with custom style names added by `@BindStyleNames`. Style class `linkki-has-icon` is not used anymore and will be removed in later version. _(since 2.1.1)_
