:jbake-title: Manual Binding With `@Bind`
:jbake-type: section
:jbake-status: published

:source-dir: ../../../../../../samples/binding/src/main/java

[[manual-binding]]
=== Manual Binding With `@Bind`

Due to special requirements or custom `Fields` it is sometimes not possible to use the <<pmo-uisection, automatic creation via `@UISection`>>. For this case *linkki* offers the option of 'only' using the data binding. This way, control over creation, arrangement and configuration (e.g. `setNullRepresentation()` or `setConverter()`) of the component is kept.

To activate the manual binding the component must be marked with the `@Bind` annotation. Both fields and methods can be annotated. Supported types are:

* `com.vaadin.ui.Field`
* `com.vaadin.ui.Label`
* `com.vaadin.ui.Button`

Then, the data binding can be created via the <<missing-link, `Binder`>>.


.@Bind on Fields
[source,java]
----
include::{source-dir}/org/linkki/samples/binding/components/AddressFields.java[tags=addressFields-class]
----

.@Bind on Methods
[source,java]
----
include::{source-dir}/org/linkki/samples/binding/components/AddressFields2.java[tags=addressFields-methodBinding]
----

TIP: When the data binding of a Vaadin component of a third party library should be used by *linkki*, it can be activated via inheritance of 'delegate proxies' and `@Bind` on the methods.

.Binding Activation
[source,java]
----
include::{source-dir}/org/linkki/samples/binding/components/ContactComponent.java[tags=manual-binding]
----

<<missing-link, Here>> is a sample project with the different binding options.

[TIP]
====
Binding summary:

* `@UISection` -> simple and quick template with limited configuration options
* manual binding -> full control

*linkki* uses certain <<missing-link, naming conventions>>. That way sources of errors and refactoring complexity are reduced.

The values used in the annotations for `pmoProperty` and `modelAttribute` should be defined as constants in the corresponding classes.
====
