:jbake-title: Tooltips
:jbake-type: section
:jbake-status: published

[[tooltips]]
=== Tooltips

For displaying tooltips on UI elements *linkki* provides the annotation `@UITooltip`. This annotation can be added in the PMO binding to the method to which the UI element is bound. In the case of binding using the `@Bind` annotation, `@UITooltip` musst be written directly in the field annotated with `@Bind`.

The `@UITooltip` annotation has two properties:

* <<tooltip-text, `text: String`>>
* <<tooltip-type, `toolTipType: ToolTipType`>>

[[tooltip-text]]
==== Text
This is the text displayed on <<tooltip-type, `ToolTipType.STATIC`>>. Its default value is an empty string (`""`).

[[tooltip-type]]

==== ToolTipType
The following configuration options are available for `ToolTipType`:

[cols="1,9"]
.ToolTipType
|===
|`STATIC`   |the text of the tooltip is read from the attribute `text` (*default*)
|`DYNAMIC`  |the text of the tooltip is determined by the return value of the method `String get<PropertyName>ToolTip()`. The value of `text` is ignored.
|===

TIP: Tooltips can only be added to <<ui-field, fields>> and <<ui-button, buttons>>.
