:jbake-type: referenced
:jbake-status: referenced
:jbake-order: 0

// NO :source-dir: HERE, BECAUSE N&N NEEDS TO SHOW CODE AT IT'S TIME OF ORIGIN, NOT LINK TO CURRENT CODE
:images-folder-name: 01_releasenotes

=== Version 1.4.0

==== New Features and Improvements

===== New Aspect Annotation: @BindVisible
////
https://jira.faktorzehn.de/browse/LIN-2026
////

For the annotation <<bind-visible, @BindVisible>>, the `VisibleType` is set to `DYNAMIC`, determining the visible state from the PMO by invoking a method named `is[PropertyName]Visible()`. Using this annotation, it is no longer necessary to specify the `visible` property with `VisibleType.DYNAMIC` in components, e.g. `@UILabel`. The <<bind-visible, @BindVisible>> can be used on any PMO, including any PMO classes that implement the `ContainerPmo` interface (i.e. `TableSections`). Using <<bind-visible, @BindVisible>> will overrule the existing `visible` property.

===== New `BoundPropertyCreator`: `ModelBindingBoundPropertyCreator`
////
https://jira.faktorzehn.de/browse/LIN-2265
////

The annotation `@LinkkiBoundProperty` now has a default value of the type `ModelBindingBoundPropertyCreator`. Using this `BoundPropertyCreator` it is very simple to create a new @UI-Field Annotation with model binding support. For more information read the corresponding documentation about <<bound-property, BoundProperty>>.

===== Concept of `BindingDefinition` is deprecated
////
https://jira.faktorzehn.de/browse/LIN-2093
////

The concept of `BindingDefinition` is deprecated because it was replaced. Therefore, the following classes and interfaces are deprecated and should not be used anymore. 

* `org.linkki.core.binding.descriptor.bindingdefinition.BindingDefinition` and all extending classes
* `org.linkki.core.binding.descriptor.bindingdefinition.annotation.LinkkiBindingDefinition`
* `org.linkki.core.uicreation.BindingDefinitionComponentDefinition`
* `org.linkki.core.ui.element.annotation.FieldAspectDefinitionCreator`

If you have built your own custom annotations using `BindingDefinition`, you should consider refactoring them using the new concept described in <<custom-ui-element-annotation,Creating a custom UI element>>

===== Faktor-IPS Property Dispatcher uses the value set information to set field properties in the UI
////
https://jira.faktorzehn.de/browse/LIN-1729
////

The `IpsPropertyDispatcher` can now derive the `required`, `visible` and `enabled` state of a field based on the value set of its model attribute. This functionality is described in the section about <<ips-property-dispatcher, IpsPropertyDispatcher>>. If the `IpsPropertyDispatcher` is already in use, this new feature will automatically come into effect with the new version.

===== Update all binding contexts in `BindingManager`
////
https://jira.faktorzehn.de/browse/LIN-573
////

`BindingManager` now has a new method `updateAll` which updates all `BindingContexts` that are managed by the `BindingManager`. This is a costly operation that should be used with caution.

==== Bugfixes

* Fixed typo in ReadOnlyBehaviorType#INVISIBLE
////
https://jira.faktorzehn.de/browse/LIN-2095
////
* Fixed log warnings due to depreacted method call in `SidebarLayout`. SidebarLayout.SelectionListener is now serializable, consider adding a serialVersionUID.
////
https://jira.faktorzehn.de/browse/LIN-2286
////
* Fixed tooltip on labels not showing HTML content  
////
https://jira.faktorzehn.de/browse/LIN-2274
////
* Fixed an error when entering a year with five or more digits
////
https://jira.faktorzehn.de/browse/LIN-2040
////