:jbake-title: PMO with UI Section
:jbake-type: section
:jbake-status: published
:source-dir: ../../../../../../samples/binding/src/main/java

[[pmo-uisection]]
=== PresentationModelObject with `@UISection`

When a class is annotated with `@UISection`, *linkki* takes control over the creation and arrangement of the defined components. Using annotations for the <<ui-element, UI elements>>, certain aspects can be defined or controlled. The sections are created via <<missing-link, `SectionFactories`>>.

The <<ui-element, `UI elements`>> are bound either to the 'properties' of a `ModelObject` or a PMO. A detailed description can be found in the chapter <<domain-model-binding, `Data on Multiple Layers`>>.

TIP: In all cases, if the `ModelObject` or PMO doesn't have a corresponding setter, the field is `readOnly`.

In the <<form-binding, first section>> the creation of a section for a 'standard' form is exemplified. In the <<binding-table, second section>> the creation of a section with a table is detailed.

[[form-binding]]
==== Binding of a Form

[[binding-model-object]]
.Binding with `@ModelObject`
[source,java]
----
include::{source-dir}/org/linkki/samples/binding/pmo/PersonSectionPmo.java[tags=personPmo-class]
----
TIP: The definition of `modelAttribute` is optional if the property name in the `ModelObject` and the name of the annotated method are equal.

[[binding-table]]
==== Binding of a Table

To create a section with a table the annotated class must implement <<ui-container-pmo, `org.linkki.core.ui.table.ContainerPmo<T>`>>. The generic parameter `T` represents the type of the PMO to create a row in this table.

[source,java]
----
include::{source-dir}/org/linkki/samples/binding/pmo/PersonTablePmo.java[tags=personTablePmo-class]
----

The method `getItems()` returns the rows of the table in the form of the previously defined `T` 'row PMOs'.

[source,java]
----
include::{source-dir}/org/linkki/samples/binding/pmo/PersonTablePmo.java[tags=personTablePmo-getItems]
----

In the `interface ContainerPmo<T>` additional `default` methods are defined. A detailed description can be found <<ui-container-pmo, here>>.

The so called 'Row PMO' is a regular PMO as described in <<form-binding, the first section>>. The only difference is that the UI elements are also annotated with <<ui-table-column, `@UITableColumn`>>.

[source,java]
----
include::{source-dir}/org/linkki/samples/binding/pmo/PersonRowPmo.java[tags=personRowPmo-labelBinding]
----

All UI elements can be used in tables. The binding of a `@UIButton` looks as follows:

[source,java]
----
include::{source-dir}/org/linkki/samples/binding/pmo/PersonRowPmo.java[tags=personRowPmo-buttonBinding]
----

NOTE: In our example the elements of the table shall be presented as read-only. Therefore no direct binding of the `ModelObject` via the `@ModelObject` annotation is done.
