:jbake-title: Create a Layout From a PMO
:jbake-type: section
:jbake-status: published
:source-dir: ../../../../../../vaadin-flow/samples/test-playground/src/main/java
:source-dir-doc: ../../../../src/main/java

[[pmo-create-layout]]
=== Create a layout from a PMO

An <<pmo-annotation, annotated PMO>> that is annotated as a <<layout, layout>> can be turned into a UI component using `UiCreator#createComponent`. The created component also contains all UI elements that are declared in the PMO. For convenience, `VaadinUiCreator` can be used instead to obtain a Vaadin `Component` instead of a `Object`.

[source,java]
----
include::{source-dir-doc}/org/linkki/doc/UiCreatorSample.java[tags=createComponent]
----

[[binding-table]]
==== Creating a table

To create a table, the PMO class must implement <<ui-container-pmo, `org.linkki.core.defaults.columnbased.pmo.ContainerPmo<ROW>`>>. The generic parameter `ROW` represents the type of the PMO to create a row in this table.

[source,java]
----
include::{source-dir}/org/linkki/samples/playground/binding/pmo/ContactTablePmo.java[tags=contactTablePmo-class]
----

The method `getItems()` returns the rows of the table in the form of the previously defined `ROW` 'row PMOs'.

[source,java]
----
include::{source-dir}/org/linkki/samples/playground/binding/pmo/ContactTablePmo.java[tags=contactTablePmo-getItems]
----

In the `interface ContainerPmo<ROW>` additional `default` methods are defined. A detailed description can be found in the section about <<ui-container-pmo, ContainerPmo>>.

The so called 'Row PMO' is a regular <<pmo, PMO>>. The only difference is that the UI elements may optionally be annotated with <<ui-table-column, `@UITableColumn`>>.

[source,java]
----
include::{source-dir}/org/linkki/samples/playground/binding/pmo/ContactRowPmo.java[tags=contactRowPmo-labelBinding]
----

All UI elements can be used in tables. The binding of a `@UIButton` looks as follows:

[source,java]
----
include::{source-dir}/org/linkki/samples/playground/binding/pmo/ContactRowPmo.java[tags=contactRowPmo-buttonBinding]
----

NOTE: In our example the elements of the table shall be presented as read-only. Therefore no direct binding of the `ModelObject` via the `@ModelObject` annotation is done. If the items of your table are provided from a model object you may consider to use `org.linkki.core.defaults.columnbased.pmo.SimpleTablePmo<MO, ROW>` which is described in chapter <<ui-tables, Tables>> in detail.

The table can then be created using `GridComponentCreator`.



If the table PMO is annotated with <<layout-section, `@UISection`>>, `UiCreator` can also be used to create a section containing the table.
