:jbake-title: Manual Binding With `@Bind`
:jbake-type: section
:jbake-status: published

:source-dir: ../../../../../../vaadin-flow/samples/test-playground/src/main/java

[[manual-binding]]
=== Manual Binding With `@Bind`

Due to special requirements or custom `Fields` it is sometimes not possible to <<pmo-create-layout, automatically create a layout with an annotated PMO>>. For this case *linkki* offers the option of 'only' using the data binding. This way, control over creation, arrangement and configuration (e.g. `setNullRepresentation()` or `setConverter()`) of the component is kept.

To activate the manual binding the component must be marked with the `@Bind` annotation. Both fields and methods can be annotated. Components based on the following classes and interfaces can be used with `@Bind`:

* `com.vaadin.flow.component.Component`
* `com.vaadin.flow.component.AbstractField<C, T>`
* `com.vaadin.flow.component.html.Label`
* `com.vaadin.flow.component.html.H2`
* `com.vaadin.flow.component.button.Button`
* `com.vaadin.flow.component.HasValue<E, V>`
* `com.vaadin.flow.data.provider.HasListDataView<T, V>`


Then, the data binding can be created via the `Binder`.


.@Bind on Fields
[source,java]
----
include::{source-dir}/org/linkki/samples/playground/binding/components/AddressFields.java[tags=addressFields-class]
----

.@Bind on Methods
[source,java]
----
include::{source-dir}/org/linkki/samples/playground/binding/components/AddressFieldsWithBindOnGetters.java[tags=addressFields-methodBinding]
----

TIP: When the data binding of a Vaadin component of a third party library should be used by *linkki*, it can be activated via inheritance of 'delegate proxies' and `@Bind` on the methods.

.Binding Activation
[source,java]
----
include::{source-dir}/org/linkki/samples/playground/binding/components/ContactComponent.java[tags=manual-binding]
----

[TIP]
====
Binding summary:

* <<layout, Layout annotations>> like `@UISection` -> simple and quick template with limited configuration options
* <<ui-creator, UiCreator>> -> automated creation and binding of individual UI components with control over the layout
* <<manual-binding, manual binding>> -> full control, but more effort and direct UI framework dependencies

*linkki* uses certain naming conventions. That way sources of errors and refactoring complexity are reduced.

The values used in the annotations for `pmoProperty` and `modelAttribute` should be defined as constants in the corresponding classes.
====
