:jbake-title: UI Element
:jbake-type: section
:jbake-status: published

:source-dir-binding: ../../../../../vaadin8/samples/binding/src/main/java
:source-dir-messages: ../../../../../vaadin8/samples/messages/src/main/java
:source-dir-dynamic: ../../../../../vaadin8/samples/dynamic-fields/src/main/java

[[ui-element]]
=== UI Element
Both fields and buttons are "UI elements". The following types are provided:

[[ui-field]]
[cols="2,6"]
.Fields
|===
|<<ui-label,`UILabel`>> |Displaying of text
|<<ui-textfield,`UITextField`>> |Field for single line text entry
|<<ui-textarea,`UITextArea`>> |Area for multiline text entry
|<<ui-numberfield,`UIIntegerField`>>, <<ui-numberfield,`UIDoubleField`>> |Entry field for numbers
|<<ui-checkbox,`UICheckbox`>> |Control for boolean input
|<<ui-datefield,`UIDateField`>> |Field for date entry with date picker
|<<ui-combobox,`UIComboBox`>> |Dropdown field with predefined options
|<<ui-yesnocombobox,`UIYesNoCombobox`>> |Dropdown field for boolean choices
|<<ui-radiobutton,`UIRadioButtons`>> |Radio buttons for selecting a single choice
|===

[[ui-buttons]]
[cols="2,6"]
.Buttons
|===
|<<ui-button,`UIButton`>> |A button that triggers an action when clicked
|===

The type of a field can be determined dynamically. This mechanism is called <<dynamicfield, dynamic field>>.

Annotations for fields and buttons must exist on methods in a PMO class. The main difference between fields and buttons is that fields are used for displaying and editing of values and thus are bound to a value via data binding. Therefore annotations for fields must exist on a getter method of a <<databinding, PMO property>>. Only if <<domain-model-binding, domain model binding>> is used the method can be named differently.

Buttons are not bound to a value, but to an annotated method. It represents an executable action which is called by the button click.

[[ui-properties]]
==== Properties
All UI elements have the following properties in common:

* <<position, `position: int`>>
* <<label, `label: String`>>
* <<enabled, `enabled: boolean`>> (not configurable for all elements)
* <<visible, `visible: boolean`>>
* <<required, `required: boolean`>> (not configurable for all elements)

<<ui-field,Fields>> have additional properties that are required for the <<domain-model-binding, domain model binding>>:

* <<model-attribute, `modelObject: String`>>
* <<model-attribute, `modelAttribute: String`>>

CAUTION: <<position, `position`>> must always be specified. For most annotations, <<label, `label`>> is also mandatory. All other properties have default values.

[[position]]
===== Position
The "position" property defines the order of elements in the UI. The relative size of the value is deciding. Elements with smaller `position` are added to a section first.

TIP: Gaps in the position numbering are allowed and common, to allow adding new UI elements at a later moment without needing to renumber all elements.
 
[[label]]
===== Label
Usually there is a label text for each UI element, that describes the element. The content of the label is defined by this attribute.

Exceptions to this are <<ui-button, buttons>> and <<ui-checkbox, checkboxes>>. These UI elements usually do not need a preceding label. Instead, the description of a button is displayed on the button itself while the description of the checkbox is commonly displayed at the right of the checkbox. This kind of describing element can be configured with the property `caption` in both annotations respectively. Buttons and checkboxes can still be configured with a label additionally by overwriting the `label` property.

If not label/caption is set, the default value `"derived.by.linkki"` kicks in and *linkki* uses the capitalized property name as label/caption.

NOTE: If an independent label is needed, the UI element <<ui-label, UILabel>> can be used.

[[enabled]]
===== Enabled
The property `enabled` controls whether a component is active/editable. The following configuration options are available:

[cols="1,8"]
.EnabledType
|===
|`ENABLED`  |the content of the element is modifiable in the UI (*default*)
|`DISABLED` |the content of the element is not modifiable in the UI
|`DYNAMIC`  |whether the content is modifiable is controlled by the return value of the method `boolean is<PropertyName>Enabled()`
|===

NOTE: A <<ui-label, UILabel>> doesn't offer these options and is always `ENABLED`.

[[visible]]
===== Visible
The property `visible` controls whether the component is visible. There are the following configuration options:

[cols="1,7"]
.VisibleType
|===
|`VISIBLE`   |the UI element is visible (*default*)
|`INVISIBLE` |the UI element is invisible
|`DYNAMIC`   |whether the UI element is visible is controlled by the return value of thte method `boolean is<PropertyName>Visible()`
|=== 

[[required]]
===== Required
The property `required` visually highlights required fields. The following configuration options are available:

[cols="1,3"]
.RequiredType
|===
|`REQUIRED`              |the UI element requires input (a value must be entered/selected)
|`REQUIRED_IF_ENABLED`   |the UI element requires input if it is `enabled`
|`NOT_REQUIRED`          |input in the UI element is optional (*default*)
|`DYNAMIC`               |whether the element requires input is controlled by the return value of the method `boolean is<PropertyName>Required()`
|===

NOTE: <<ui-label, UILabels>> und <<ui-button, UIButtons>> do not offer these options and are always `NOT_REQUIRED`.

WARNING: Fields marked as `required` are only visually highlighted. *No* validation is performed.

[[model-attribute]]
===== ModelObject and -Attribute
A <<ui-field, field>> can be bound to an attribute of an existing model object using <<domain-model-binding, domain model binding>>. For this the properties `modelAttribute` and possibly `modelObject` are required. The function is described in the section <<model-attribute-names, names of model attributes>>.

[[ui-label]]
==== UILabel
The annotation `@UILabel` generates an independent UI element displaying `String` content. In contrast to a deactivated <<ui-textfield, UITextField>> its text is not framed by an input field. This annotation is equivalent to a `com.vaadin.ui.Label`.

The annotated method must return a value of `String` type. The return value defines what is shown as label.

TIP: A `UILabel` also has the additional property <<label,`label`>>. If a value is set to it the text would appear beside the `UILabel`.

===== HTML Content
The content of the label can be styled with HTML if `htmlContent=true` is specified.

.Example HTML Label Content
[source, java]
----
include::{source-dir-binding}/org/linkki/samples/binding/pmo/ContactRowPmo.java[tags=contactRowPmo-labelHtmlContent]
----

[[label-style-names]]
===== Styles
To style labels the property `styleNames` can be used to specify a list (actually a `String[]`) of CSS class names.

[[ui-checkbox]]
==== UICheckbox
A `com.vaadin.ui.CheckBox`, bound to a boolean property.
Instead of a label on the left side of the UI element, checkboxes usually have a caption on the right. This caption must be set with the property `caption`. If no caption is desired, an empty String must be set. 

The usual `label` property is still available if any display text is needed on the left side additionally.

When used in a table, the `label` is used as the column name while the `caption` is displayed next to the checkbox in the table cell.

[[ui-textfield]]
==== UITextField
A `com.vaadin.ui.TextField` for text entry. The annotation `UITextfield` has two additional properties:

* `maxLength: int`
* `width: String`

`maxLength` defines the maximum number of characters that can be entered or displayed in the field while `width` defines the visible width of the field using a number and a CSS unit, for example "5em" or "50%". This value is set to 100% by default which means it grabs the available space.

TIP: For Vaadin 7, the property `columns: int` defines the width of the text field. If no positive value is defined, all available space is used.

[[ui-textarea]]
==== UITextArea
The annotation `UITextArea` corresponds to a `com.vaadin.ui.TextArea`. It is used for entering or displaying text that has more than one line.`UITextArea` has all the properties of the annotation `UITextfield`. In addition, it also has: 

* `rows: int`

The property `rows` defines the height of the `UITextArea`, not how many rows can be entered. Its default value is `1`.

[[ui-numberfield]]
==== UIIntegerField and UIDoubleField
`@UIIntegerfield` and `@UIDoubleField` are text fields for displaying formatted numbers. Like <<ui-textfield,`@UITextField`>> these annotations have the property `maxLength`.

The format can be defined with the property `format: String`, using the notation from `java.text.NumberFormat`.

If no format is specified for a `UIIntegerField`, *linkki* uses the default Java Integer NumberFormat (`java.text.NumberFormat#getIntegerInstance(java.util.Locale)`). In the case of `UIDoubleField` the format `\#,\##0.00##` is used by default. This format means that at least one digit is displayed before the decimal separator and two after, plus thousands separator. The documentation for the format definition can be looked up in the class `java.text.DecimalFormat`.

[[ui-datefield]]
==== UIDateField
The annotation `@UIDateField` generates a date input field and corresponds to `com.vaadin.ui.DateField`. It allows specifying a date format using the property `dateFormat: String`. If not date format is defined the format matching the `Locale` setting is used. *linkki* uses `"dd.MM.yyyy"` by default for German. For other languages `DateFormat.SHORT` from the JDK is used.
When the <<widgetset,*linkki* widgetset>> is used, a `MultiformatDateField` is created instead. It allows multiple date formats to be set and by default uses the same date format as the standard Vaadin date field but also allows dates without punctuation to be entered, so that for example `010420` becomes `01.04.2020`.

TIP: With Vaadin 7, the property can return both `java.time.LocalDate` and `org.joda.time.LocalDate` when the matching converters are set in the `LinkkiConverterFactory`.

[[ui-combobox]]
==== UIComboBox
A `@UIComboBox` allows selection of a value from a list. It has three additional properties:

* <<ui-combobox-content,`content: AvailableValuesType`>>
* <<ui-combobox-width,`width: String`>>
* <<itemCaptionProvider, `itemCaptionProvider: Class<? extends ItemCaptionProvider<?>>`>>

[source, java]
----
include::{source-dir-dynamic}/org/linkki/samples/dynamicfield/pmo/CarPmo.java[tags=ui-combobox]
----

[[ui-combobox-content]]
===== Content
The attribute `content` defines which values are available:

[cols="4,11"]
.AvailableValuesType
|===
|`ENUM_VALUES_INCL_NULL` |the values of the combobox correspond to the values of the enum data type of the property, extended by the value `null` (*default*)
|`ENUM_VALUES_EXCL_NULL` |the values of the combobox correspond to the values of the enum data type of the property
|`DYNAMIC`               |the values of the combobox are defined dynamically through the method `Collection<T> get<PropertyName>AvailableValues()`
|`NO_VALUES`             |this combobox has no selectable values
|===

[[ui-combobox-width]]
===== Width
The property `width` can be used to define the width of the combobox using CSS syntax (e.g. `"25em"` or `"100%"`). The default value is `-1px`, corresponding to the standard size given by Vaadin.

[[itemCaptionProvider]]
===== ItemCaptionProvider
For displaying the individual values in the combobox a `org.linkki.core.defaults.ui.element.ItemCaptionProvider<T>` is used. By default it is a `DefaultCaptionProvider` that expects a method `getName()`. Via the property `itemCaptionProvider` an alternative implementation class can be specified. *linkki* offers two additional ones: 

* `ToStringCaptionProvider`: uses the `toString()`method of the elements
* `IdAndNameCaptionProvider`: displays name and ID in the format `"name [ID]"` using the methods `getName()` and `getId()`.

[[ui-yesnocombobox]]
==== UIYesNoComboBox
A `@UIYesNoComboBox` allows selection of a boolean value from a dropdown list like a <<ui-combobox, `UIComboBox`>>. The difference is that the values are not a generic enumeration or list but the well known boolean values `true` and `false` (and for `Boolean`, the option `null`). It has two properties known from the <<ui-combobox, `UIComboBox`>>:

* <<ui-combobox-width,`width: String`>>
* <<itemCaptionProvider, `itemCaptionProvider: Class<? extends ItemCaptionProvider<?>>`>> with a default implementation `BooleanCaptionProvider` that uses common names in the current locale like "Yes"/"No" or "Ja"/"Nein".

[[ui-radiobutton]]
==== UIRadioButtons
`@UIRadioButtons` allow selection of a single value using a group of buttons. Multiple values cannot be selected at the same time.

* <<ui-combobox-content,`content: AvailableValuesType`>>
* <<itemCaptionProvider, `itemCaptionProvider: Class<? extends ItemCaptionProvider<?>>`>> with a default implementation `DefaultCaptionProvider` that delegates to `getName` or `toString`
* `buttonAlignment: AlignmentType`

[[ui-subsetchooser]]
==== UISubsetChooser
For selection of multiple values from a list, *linkki* offers the `@UISubsetChooser`. In this UI control elements are selected by moving them from a list on the left to a list on the right. The display of the individual elements is similar to <<itemCaptionProvider, `UIComboBox`>>, but with a default of `ToStringCaptionProvider`. As with <<ui-combobox-width, UICombobox>> the width can be defined via the property `width`.

The content of a subset chooser must be specified with the method `Collection<T> get<PropertyName>AvailableValues()`. The bound property must be of type `Set<T>`.

The caption of both columns can be set through the properties `leftColumnCaption: String` and `rightColumnCaption: String`.

[[ui-customfield]]
==== UICustomField
Other controls can also easily be generated and bound by *linkki*. For this the annotation `@UICustomField` is used. 

The control class is specified with the property `uiControl: Class<? extends Field<?>>`. If the control implements `com.vaadin.data.HasItems<T>` the values can be defined by `content: AvailableValuesType` like with <<ui-combobox,UIComboBox>>.

WARNING: `@UICustomField` only supports controls with a parameter-less constructor.

.UICustomField Example: PasswordField
[source,java]
----
include::{source-dir-messages}/org/linkki/samples/messages/pmo/RegistrationSectionPmo.java[tags=ui-custom-field]
----

TIP: For Vaadin 7, available values are bound for components inheriting from `com.vaadin.ui.AbstractSelect`

[[dynamicfield]]
==== Dynamic Field

*linkki* allows for dynamic typing of an input field. In the following example `Retention` should only be freely writable if `CarType` is set to `STANDARD`. Otherwise the user can only select values from a list:

[source,java]
----
include::{source-dir-dynamic}/org/linkki/samples/dynamicfield/pmo/CarPmo.java[tags=ui-dynamic-field]
----
The selectable UI elements are defined via annotations on the method, as is customary. They must, however, fulfill the following requirements, to allow the type to be determined dynamically:

1. the `position` in the UI* annotations must match
2. the `label` must have the same value

If the `position` values are identical but the `label` values differ, an exception is thrown.

Which UI element is displayed for each PMO instance is determined by the method `Class<?> get<PropertyName>ComponentType()`. It returns the class of the UI*-Annotation for the UI control to be rendered.

[[ui-button]]
==== UIButton

The annotation `@UIButton` is used to mark the method that should be executed with the click on the button. 

Buttons are not bound to values. Since buttons therefore have no corresponding PMO property, the name of the annotated method is used to determine the associated methods. The behavior is similar to the  <<domain-model-binding, domain model binding>>, although buttons have no property `modelAttribute`.

[source,java]
----
include::{source-dir-binding}/org/linkki/samples/binding/pmo/ButtonsSectionPmo.java[tags=button]
----

Apart from the <<ui-properties, common properties>>, buttons have these additional ones:

* <<caption, caption: String>>
* <<caption, captionType: CaptionType>>
* <<icon, icon: FontAwesome>>
* <<icon, show-icon: boolean>>
* <<button-style-names, styleNames: String[]>>
* <<button-key-binding, shortcutKeyCode: int>>
* <<button-key-binding, shortcutModifierKeys: int[]>>

[[caption]]
===== Caption

The text shown on a button is called a caption. It is not to be confused with a <<label, Label>>, which usually appears besides the control. A button can have both a caption and a label text.

* *`captionType: CaptionType`*

[cols="1,9"]
.CaptionType
|===
|`STATIC`  |the caption of the button is read from the attribute `caption` (*default*)
|`NONE`    |the button has no caption
|`DYNAMIC` |the caption of the button is determined by the return value of the method `String get<PropertyName>Caption()`. The value of the attribute `caption` is ignored.
|===

[[icon]]
===== Icon
Apart from captions, buttons can be adorned with icons. For this the constants of the Vaadin class `VaadinIcons` are used. For the icon to be displayed the property `showIcon` must be set `true`.

TIP: Vaadin 7 used `FontAwesome` instead of `VaadinIcons`.

[[button-style-names]]
===== Style Names
Depending on the function buttons must be styled differently. A typical example for this is the link button, a button that looks like a link. For this purpose the annotation `@UIButton` has the property `styleNames`. The value of this property are the CSS class names that should apply to the button.

[[button-key-binding]]
===== Key Bindings
Some buttons shouldn't be triggered only by mouse click, but also by key combinations. These can be specified with the properties `shortcutModifierKeys` and `shortcutKeyCode`. `shortcutModifierKeys` defines which keys must be pressed and held before the key in the `shortcutKeyCode` is pressed. For instance, in many applications saving is triggered with the shortcut combination "Ctrl + s". In this case the "Ctrl" key is the modifier and the "s" key is the ShortcutKey.

In both properties individual keys are identified by integer values. The appropriate value for each key can be found in the Vaadin classes `ModifierKey` and `KeyCode`.