:jbake-title: Additional Binding
:jbake-type: section
:jbake-status: published
:source-dir: ../../../../../../vaadin8/samples/binding/src/main/java

=== Additional Binding

[[tooltips]]
==== Tooltips

For displaying tooltips on UI elements *linkki* provides the annotation `@BindTooltip`. This annotation can be added in the PMO binding to the method to which the UI element is bound. In the case of binding using the `@Bind` annotation, `@BindTooltip` must be written directly in the field annotated with `@Bind`.

The `@BindTooltip` annotation has two properties:

* <<tooltip-text, `value: String`>>
* <<tooltip-type, `tooltipType: TooltipType`>>

[[tooltip-text]]
===== Value
This is the text displayed on <<tooltip-type, `TooltipType.STATIC`>>. Its default value is an empty string (`""`).

[[tooltip-type]]

===== TooltipType
The following configuration options are available for `TooltipType`:

[cols="1,9"]
.TooltipType
|===
|`STATIC`   |the text of the tooltip is read from the attribute `value` (*default*)
|`DYNAMIC`  |the text of the tooltip is determined by the return value of the method `String get<PropertyName>Tooltip()`. The `value` is ignored.
|===

TIP: Tooltips can only be added to <<ui-field, fields>> and <<ui-button, buttons>>.

[source,java]
----
include::{source-dir}/org/linkki/samples/binding/pmo/ContactRowPmo.java[tags=contactRowPmo-buttonBinding]
----

[[bind-read-only]]
==== Bind Read-Only State

To change a component's read-only behavior, *linkki* provides the annotation `@BindReadOnly`. This annotation can be used in combination with  @Bind or UI-annotations.

IMPORTANT: The `@BindReadOnly` annotation must be placed after `@Bind` or `@UI-annotations` as the read-only state might have already been affected by these annotations.

TIP: This annotation should be used only in exceptional cases, since most of the behavior is better controlled by a <<cross-sectional-binding, PropertyBehavior>>.

The `@BindReadOnly` Annotation has only one property, `ReadOnlyType`. Per default, `ReadOnlyType#ALWAYS` is selected. Following `ReadOnlyTypes` are available:

[cols="1,9"]
.ReadOnlyType
|===
|`ALWAYS`   |the component is always read-only (*default*)
|`DYNAMIC`  |the read-only behavior of the component is determined by the return value of the method `is<PropertyName>ReadOnly()`
|`DERIVED`  |behavior as it would be without this annotation
|===
