:jbake-title: Tables
:jbake-type: section
:jbake-status: published

:source-dir-binding: ../../../../../../samples/binding/src/main/java
:source-dir-dynamic: ../../../../../../samples/dynamic-fields/src/main/java


[[ui-tables]]
=== Tables

The basics of table creation were already mentioned in the chapter <<binding-table, binding of a table>>. This section details the <<ui-row-pmo,definition of table structure>>, the <<ui-container-pmo, `ContainerPmo<T>`>>, the <<ui-simple-item-supplier, `SimpleItemSupplier<PMO, MO>`>> and the <<ui-table-footer, `TableFooter`>>.

[[ui-row-pmo]]
==== Definition of the table structure with a row PMO
The structure of the table is defined in a PMO class, whose instances represent rows in the table. Thus, these classes are called "row PMOs".

Row PMO classes are standard PMOs, which do not represent sections and thus shouldn't be annotated with `@UISection`.

Here, the annotation <<ui-element,UI element>> defines the column in the table. A column showing the name of a person, for instance, can be setup as follows:

[source, java]
----
include::{source-dir-binding}/org/linkki/samples/binding/pmo/PersonRowPmo.java[tags=personRowPmo-labelBinding]
----

[[ui-table-column]]
===== @UITableColumn

By design all properties of a PMO are presented in the table. With the annotation `@UITableColumn` the column width can be set via the properties `width` (in pixels) or `expandRatio`.

NOTE: If both properties are set, `width` has a higher priority than `expandRatio`.

[[ui-container-pmo]]
==== ContainerPmo

A `ContainerPmo` is a class that implements the interface `ContainerPmo<T>` and is annotated with `@UISection`. The main function of a `ContainerPmo` is providing the PMOs to be rendered in the table. 

The method `List<T> getItems()` is called by the `TableBinding` to add the elements to the table. It should always return the same instance of `List<T>`. The <<ui-simple-item-supplier, `SimpleItemSupplier`>> offers support for that.

By overwriting the `default` method `int getPageLength()` the number of lines shown can be controlled. By default 15 lines are shown. It is a common tactic to allow tables to 'grow' to a certain size and then limit the number of lines while also enabling the scrolling for the table. If `0` is returned the table grows dynamically with the content, without limit.

```java
include::{source-dir-binding}/org/linkki/samples/binding/pmo/PersonTablePmo.java[tags=page-length]
```

The column structure of the table is determined by the class <<ui-row-pmo, row PMO>>, which is returned by the method `Class<? extends T> getItemPmoClass`. In the default implementation the class of the generic parameter `T` is returned. For tables that should have the same rows but different columns, this method can be overwritten to use a subclass of `T`.

If the table should support the adding of items, the `default` method `Optional<ButtonPmo> getAddItemButtonPmo` must be overwritten. How a `ButtonPmo` is created is described in the chapter <<button-pmo, ButtonPmo>>.

[[ui-simple-item-supplier]]
==== SimpleItemSupplier

The `SimpleItemSupplier<PMO, MO>` is used to only create a new `List<PMO>`, if a row was changed.

The instancing is done with two parameters

* `modelObjectSupplier` of type `Supplier<List<MO>>` is called to access a list of the model objects
* `mo2pmoMapping` of type `Function<MO, PMO>` is called for the creation of a PMO for a model objects

.Example initialising of a SimpleItemSuppliers
[source, java]
----
include::{source-dir-binding}/org/linkki/samples/binding/pmo/PersonTablePmo.java[tags=item-supplier]
----

[[ui-simple-table-pmo]]
==== SimpleTablePmo

Most commonly, the row PMO objects are converted from a list of model objects. In this case, the abstract class `org.linkki.core.ui.table.SimpleTablePmo<MO, ROW>` may be extended. This abstract class defines a constructor that requires the list or the supplier for the list of model objects. Additionally the method `createRow(MO)` needs to be implemented. This method simply get a model object and creates a row PMO for it. The same example as in the previous section may look like this:

[source, java]
----
include::{source-dir-binding}/org/linkki/samples/binding/pmo/SimplePersonTablePmo.java[tags=simplePersonTablePmo]
----

[[ui-table-footer]]
==== TableFooterPmo

By overwriting the `default` method `getFooterPmo()` a footer row is generated. The implementation of the interface `TableFooterPmo` must implement the method `getFooterText(String column)`.

The parameter `column` is the ID of the column for which the text should be displayed. An example for this would be a sum of all items from a column.

```java
include::{source-dir-dynamic}/org/linkki/samples/dynamicfield/pmo/CarTablePmo.java[tags=table-footer]
```

[[button-pmo]]
==== ButtonPmo
Currently the <<ui-container-pmo, `ContainerPmo`>> provides a method `getAddItemButtonPmo()`, by which a plus button can be added besides the name of the table. This part ofthe API is being refactored in the issue LIN-128.