:jbake-title: New & Noteworthy
:jbake-type: chapter
:jbake-status: published
:jbake-order: 0

== New & Noteworthy

=== ???

==== *linkki* is getting independant of cdi

All dependencies to and usages of CDI have been removed from linkki core and utils to better allow linkki's usage in different environments.
 * The interface `AutoDiscoveredConverter` has been removed; Converters must now be manually registered in the `ApplicationFrame#getConverters` method
 * The `LinkkiConverterFactory` now accepts a sequence supplier as its constructor and offers a default sequence containing the Java 8 date converters
 * The Joda date converters can be now found in the `JodaConverters#DEFAULT_JODA_DATE_CONVERTERS`
 * The package `org.linkki.util.cdi` and its children have been removed
 

=== April 10th, 2018

==== NLS Service

linkki now always use `DefaultPmoNlsService` as `PmoNlsService` and `DefaultNlsService` as `NlsService`. That means custom implementations of these interfaces are not automatically used by linkki anymore. If an individual implementation of these classes were/have to be used, please contact the linkki development team.
 
==== BeanInstantiator

`org.linkki.util.cdi.BeanInstantiator` is deprecated and will be removed the next release. Instead, use `org.apache.deltaspike.core.api.provider.BeanProvider`. Test cases which need the CDI environment provided by `BeanInstantiator` can extend `TestWithBeanProvider` from `f10-commons-cdi-test`:

            <dependency>
                <groupId>de.faktorzehn.commons</groupId>
                <artifactId>f10-commons-cdi-test</artifactId>
                <version>18.7.0</version>
            </dependency>

=== March 22th, 2018

==== No More Binding Private Methods

Previously, linkki allowed some annotations to be used on non-public methods when using `Binder` to manually create bindings. This is no longer possible, as we believe that all methods used by linkki's binding should be public and not be accessed by reflection hacks. 

=== February 15th, 2018

==== Binding Aspects

The binding mechanism was redesigned fundamentally. Everything that could be bound to a component such as the value, the enabled state, the visible state, available values etc. are now configured by so called binding aspects. This new mechanism makes it easier to include other UI component properties into the dynamic binding mechanism. It also greatly simplify the process of implementing custom binding aspects.

Due to the refactoring we could simplify and consolidate several classes. If you have created your own binding annotations or a customized property dispatcher chain there may be some need of adaption:

. The interface `UIElementDefinition` is merged into `BindingDefinition`. Its implementations such as `UIFieldDefinition` are removed. If you have implemented your own field annotation that implements `UIElementDefinition` or `UIFieldDefinition`, just implement `BindingDefinition` directly instead. In addition to your `@LinkkiBindingDefinition` annotation you have to specify the bound aspects using `@LinkkiAspect` annotation. You could use the composite aspect `FieldAspectDefinition` which defines the most common aspects for `AbstractFields`. The aspect for available values is no longer retrieved via `BindingDefinition`. If you want to include this aspect just create a subclass of `AvailableValuesAspectDefinition` that suits your annotation and add it to your custom annotation using `@LinkkiAspect`.
. The `AnnotationDispatcher` is renamed to `StaticValueDispatcher`
. The implementations of `BindingDescriptor` are merged into `ElementDescriptor` for all field bindings. `BindAnnotationDescriptor` is used for the special case of `@Bind` annotation.
. The subclasses of `ElementBinding` for components are united to `ComponentBinding`.

We decided to not keep the deprecated implementations because the refactoring changes will have little effect on client code and keeping deprecated classes would significantly increase maintenance effort.

=== January 15th, 2018

==== `open()` in `OkCancelDialog`

With the new method `open()` in `OkCancelDialog`, a dialog can be directly opened by calling `dialog.open()` instead of using `PmoBasedDialogFactory.open(dialog)`. The `open()` method can be extended to add additional behaviors to the dialog. By default, a `UriFragmentChangedListener` is added upon opening, ensuring that the dialog is properly closed on URL change. If this behavior should be adapted, make sure that all existing dialogs are opened using the new `open()` method.

The `open(OkCancelDialog)` method in `PmoBasedDialogFactory` is deprecated and will be removed in the future.

=== Januar 14th, 2018

==== Changed package for PropertyBehavior

The class `PropertyBehavior` was moved from `org.linkki.core.binding.aspect` to `org.linkki.core.binding.behavior`.

=== January 10th, 2018

==== New component Headline

A new standard component for the application framework called `org.linkki.framework.ui.component.Headline` was introduced. It is used to show a headline at the top of a page below the application header. For customizing it is intended to subclass `Headline` and add further components.

For styling the `Headline` there is a new stylesheet class called `linkki-headline`.

==== OkHandler now deprecated

The interface `OkHandler` is no longer used by *linkki* and will be removed in version 1.0. The already existing interface `Handler` has the same functionality and should be used instead.

==== Annotation @UISection optional

The annotation `@UISection` is now optional. If a class without that annotation is used as a PMO, the annotation's default values (column layout with one column, no caption, not closable, id equal to the class' simple name) are used for the resulting section.


=== December 12th, 2017

==== Captions for Checkboxes

*linkki* versions up to 0.9.20171123 treated checkboxes like any other input field concerning labels: The label is displayed on the left, preceding the input field. But in most UI layouts, checkboxes are followed by a caption instead. To facilitate this layout, the `@UICheckBox` now has a `caption` property that must be set. The old `label` can still be used, but the default value for `noLabel` has been switched to `true`, so that `nolabel=false` has to be used where a label should be displayed.

If a `@UICheckBox` is used in a table column and `nolabel=false` is set, the label is displayed as the column header, while the caption remains at the right of the individual checkboxes in the table cells.
