:jbake-title: New & Noteworthy
:jbake-type: chapter
:jbake-status: published
:jbake-order: 0

== New & Noteworthy

image::https://maven-badges.herokuapp.com/maven-central/org.linkki-framework/linkki-core/badge.svg[Maven central]

=== 15. January 2018

==== `open()` in `OkCancelDialog`

With the new method `open()` in `OkCancelDialog`, a dialog can be directly opened by calling `dialog.open()` instead of using `PmoBasedDialogFactory.open(dialog)`. The `open()` method can be extended to add additional behaviors to the dialog. By default, a `UriFragmentChangedListener` is added upon opening, ensuring that the dialog is properly closed on URL change. If this behavior should be adapted, make sure that all existing dialogs are opened using the new `open()` method.

The `open(OkCancelDialog)` method in `PmoBasedDialogFactory` is deprecated and will be removed in the future.

=== 14. Januar 2018

==== Changed package for PropertyBehavior

The class `PropertyBehavior` was moved from `org.linkki.core.binding.aspect` to `org.linkki.core.binding.behavior`.

=== 10. January 2018

==== New component Headline

A new standard component for the application framework called `org.linkki.framework.ui.component.Headline` was introduced. It is used to show a headline at the top of a page below the application header. For customizing it is intended to subclass `Headline` and add further components.

For styling the `Headline` there is a new stylesheet class called `linkki-headline`.

==== OkHandler now deprecated

The interface `OkHandler` is no longer used by *linkki* and will be removed in version 1.0. The already existing interface `Handler` has the same functionality and should be used instead.

==== Annotation @UISection optional

The annotation `@UISection` is now optional. If a class without that annotation is used as a PMO, the annotation's default values (column layout with one column, no caption, not closable, id equal to the class' simple name) are used for the resulting section. 


=== 12. December 2017

==== Captions for Checkboxes

*linkki* versions up to 0.9.20171123 treated checkboxes like any other input field concerning labels: The label is displayed on the left, preceding the input field. But in most UI layouts, checkboxes are followed by a caption instead. To facilitate this layout, the `@UICheckBox` now has a `caption` property that must be set. The old `label` can still be used, but the default value for `noLabel` has been switched to `true`, so that `nolabel=false` has to be used where a label should be displayed.
 
If a `@UICheckBox` is used in a table column and `nolabel=false` is set, the label is displayed as the column header, while the caption remains at the right of the individual checkboxes in the table cells.