:jbake-title: Latest
:jbake-type: section
:jbake-status: published
:jbake-order: 0

// NO :source-dir: HERE, BECAUSE N&N NEEDS TO SHOW CODE AT IT'S TIME OF ORIGIN, NOT LINK TO CURRENT CODE
:images-folder-name: 01_newnoteworthy

++++
<style>
// Should be created as a separate CSS file for a custom jbake-type

.api-change > h5:after,
.api-change > h4:after,
.api-change > h3:after {
  content: 'api-change';
  color: white;
	margin-left: 1em;
	font-weight: bold;
	border-radius: 2px;
	background: #009fe3;
	padding: .3em 1em;
	font-size: .8em;
	box-shadow: 1px 1px 5px rgba(0,0,0,0.1);
}

.sect3 {
	margin-bottom: 4em;
}

details > summary {
	display: list-item;
}

details > div {
  padding-left: 1em;
  margin-left: .2em;
  border-left: 3px #eee solid;
}
</style>
++++

=== {dversion}

===== BindingManager#get~Context

The `getExtistingContext` and `getExistingContextOrStartNewOne` methods of the `BindingManager` have been deprecated in favor of the shorter `getContext` methods, which do the same as the old `getExistingContextOrStartNewOne` methods. It is no longer considered necessary to get an `Optional<BindingContext>` as the creation of the context is rather cheap and would happen sooner or later anyways.

Existing code can be migrated via link:../migration_scripts/0.9.20190418_to_latest/migrate.sed[0.9.201901418_to_latest/migrate.sed].
