:jbake-title: Displaying Validation Messages
:jbake-type: section
:jbake-status: published

:source-dir-messages: ../../../../../vaadin8/samples/messages/src/main/java

[[displaying-validation-messages]]
=== Displaying Validation Messages

By default *linkki* marks UI elements bound to invalid <<object-properties, ObjectProperties>>. The input field bound to the referenced `ObjectProperty` shows a colored border and background as well as a tooltip displaying the validation messages for that field. 

However, *linkki* does not provide a UI element to display all validation messages returned by a `ValidationService`. In order to display these messages a custom UI component has to be created along with a `BindingManager`. The `BindingManager` must override its `updateMessages` method that gets called after validation. A common pattern here is to use a `Consumer<MessageList>` as an argument to the `BindingManager` to decouple it from the actual custom UI component (which implements `Consumer<MessageList>`).

[source, java]
----
include::{source-dir-messages}/org/linkki/samples/messages/binding/RegistrationBindingManager.java[tags=binding-manager-update-messages]
----

Usage:

[source, java]
----
include::{source-dir-messages}/org/linkki/samples/messages/MessageUI.java[tags=validation-service]
----