:jbake-title: Step 11: UI Tests
:jbake-type: section
:jbake-status: published
:jbake-order: 13

:source-dir: ../../../../../samples/tutorial-application/src/test/java/org/linkki/samples/appsample

[[tutorial-step-11]]
=== Step 11: UI Tests

[NOTE]
This step shows you how to write UI tests (using **Karibu-Testing**) for the components written in linkki.

=== KaribuUIExtension

Let’s start with writing UI tests for `BusinessPartnerView` .

Create a test class named `BusinessPartnerViewTest`:

.BusinessPartnerViewTest.java
[source,java,indent=0]
----
include::{source-dir}/view/BusinessPartnerViewTest.java[tags=businessPartnerViewTest]
----

The annotations on the test class instantiate a Vaadin UI for testing and configure the default locale.

==== Testing the BusinessPartnerView

As a first test, you should test the *search functionality* of the `BusinessPartnerView`.
The test should:

- Programmatically enter a value in the search field
- Click the search button
- Verify the results

Access the UI components by using the static method `LocatorJ._get`.
It is recommended to use the utility methods provided in `KaribuUtils`, as they offer more convenient and robust options for interacting with the UI.

The following example shows how to search for a partner and check if a matching result is present.

.BusinessPartnerViewTest.java - Search returns results
[source,java,indent=0]
----
include::{source-dir}/view/BusinessPartnerViewTest.java[tags=testSearchFieldWithResult]
----

[IMPORTANT]
====
Always use `KaribuUtils.Fields.setValue()` to update field values.
Calling `setValue()` directly on a component does *not* trigger the linkki binding mechanism.
====

As you can see in the example, the _get-function obtains the search field from the BusinessPartnerView by its ID `searchText`.
The ID of a component created by linkki is the name of the corresponding PMO <<pmo, property>>.

KaribuUtils also provides convenient functions to extract all values from a column as strings.
As you can see, this is used to acquire the names and addresses written in the name and address column, allowing to write assertions for those values.

Now, write a test case, where the search yields no result because there is no business partner matching the search criteria.
Once you are done, it should look similar to the following example:

.BusinessPartnerViewTest.java - Search returns no results
[source,java,indent=0]
----
include::{source-dir}/view/BusinessPartnerViewTest.java[tags=testSearchFieldWithNoResult]
----

==== Testing the PartnerDetailsView

After having properly tested the search page, your next task is to test `PartnerDetailsView` as well!

PartnerDetailsView implements `HasUrlParameter`, which will require some special attention during testing.
Therefore, we have to configure Vaadin so that we can navigate to the PartnerDetailsView.

.PartnerDetailsViewTest.java
[source,java,indent=0]
----
include::{source-dir}/view/PartnerDetailsViewTest.java[tags=partnerDetailsViewTest]
----

As you can see, instead of annotating the test-class with `@ExtendWith`, you have to declare a field of type `KaribuUIExtension` and annotate that field with `@RegisterExtension`.
This way, KaribuUIExtension can be configured beyond its default configuration, and we can register a route to PartnerDetailsView.

The next test uses `UI.getCurrent().navigate(...)` to navigate to the `PartnerDetailsView` given a business partner ID.
It then tests if the business partner information is displayed correctly.

.PartnerDetailsViewTest.java - Partner exists
[source,java,indent=0]
----
include::{source-dir}/view/PartnerDetailsViewTest.java[tags=testExistingPartner]
----

Now try to write a test case yourself where no partner could be found for the given ID!

It should look like the following test:

.PartnerDetailsViewTest.java - Partner not found
[source,java,indent=0]
----
include::{source-dir}/view/PartnerDetailsViewTest.java[tags=testPartnerDoesNotExist]
----

==== Testing Dialogs and Validation-Messages

Finally, it's time to test dialogs and validation messages!

To test the dialog for adding a new address, you must:

- Navigate to the appropriate tab
- Trigger the dialog
- Interact with and write assertions for the dialog’s content

The first test should check the happy path, when all fields are set, the dialog closes properly and another entry appears in our address table.

.PartnerDetailsViewTest.java - Successful dialog submission
[source,java,indent=0]
----
include::{source-dir}/view/PartnerDetailsViewTest.java[tags=testAddAddressValid]
----

Next, you need to check that the validations work correctly.
Therefore, you can press the OK-Button right after the dialog opened and while all fields are empty.
The result should be that all fields have an error message saying that the field must not be empty.

.PartnerDetailsViewTest.java - Dialog validation
[source,java,indent=0]
----
include::{source-dir}/view/PartnerDetailsViewTest.java[tags=testAddAddressInvalid]
----

Congratulations!
You've now seen how to:

- Write simple UI tests with KaribuUIExtension,
- Test interactive components like search fields and tables,
- Handle routing and navigation in tests,
- Assert on validation messages and dialog interactions.