:jbake-type: referenced
:jbake-status: referenced
:jbake-order: 0

// NO :source-dir: HERE, BECAUSE N&N NEEDS TO SHOW CODE AT IT'S TIME OF ORIGIN, NOT LINK TO CURRENT CODE
:images-folder-name: 01_releasenotes

=== Version 1.5.0

==== New features and improvements

// https://jira.faktorzehn.de/browse/LIN-2534
* `LinkkiTabSheetBuilder#onSelectionHandler` has been removed. There are multiple <<linkkitablayout-selection, alternatives available>>.
// https://jira.faktorzehn.de/browse/LIN-2524
* `linkki-application-framework-vaadin14` now includes `linkki-vaadin14-component` and `linkki-core-nestedcomponent-vaadin14` as dependencies

==== Bugfixes

==== Usage of `@UIComboBox` with items that don't implement `equals`
// https://jira.faktorzehn.de/browse/LIN-2200

Returning new instances that do not implement `equals` in the getter or available values previously caused a loop that constantly reset the combo box.

While this problem has been fixed, it is still *not recommended* to return new instances that do not implement `equals`.
This causes problems when expanding the drop down list: Items must be loaded every single time and the selected item is not highlighted correctly.

==== Other bugfixes
// https://jira.faktorzehn.de/browse/LIN-2509
* Fixed the bug in `IpsPropertyDispatcher` that fields with an empty value set are set as required.
//https://jira.faktorzehn.de/browse/LIN-2264
* `@UILink` behaves like a label if the link location (href) is empty.
// https://jira.faktorzehn.de/browse/LIN-2555
* Fields now use the https://vaadin.com/api/platform/14/com/vaadin/flow/data/value/ValueChangeMode.html#ON_CHANGE[ValueChangeMode.ON_CHANGE] instead of https://vaadin.com/api/platform/14/com/vaadin/flow/data/value/ValueChangeMode.html#ON_BLUR[ValueChangeMode.ON_BLUR]
