:jbake-title: Aspects
:jbake-type: section
:jbake-status: published
:source-dir-playground: ../../../../../../vaadin23/samples/test-playground/src/main/java
:source-dir: ../../../../src/main/java

[[aspects]]
=== Aspects

*linkki* can bind more than just the value. In fact, almost every part of the UI state can be taken into account for data binding with *linkki*. The most common parts of the UI state are for example the enabled state or the visibility. But there are also additional features that may be bound to a component such as the tooltip, available values for selection or CSS class names. For a property, every such UI state part is a so called __aspect__ of the property.

Some aspects are crucial for the functionality of the <<ui-element, UI element>> and are thus directly <<embedded-aspects, embedded in the annotation>>. Besides those, *linkki* also provides some <<standalone-aspects, standalone aspect annotations>> that can be optionally applied to the <<ui-element, UI elements>>. 

[[aspects-usage]]
==== Aspects in a PMO

The following example shows two aspects for the property "name". 

.Value and enabled aspect
[source,java]
----
include::{source-dir}/org/linkki/doc/dynamic/PartnerSectionPmo.java[tags=aspects]
----

The most important aspect is the value aspect. It is also mandatory for the data binding to function. The value aspect is dynamically determined by the getter and setter methods of the property. As the value aspect is critical for the <<ui-element, UI element>> to function, it is always embedded in the UI element annotation.

The second aspect that can be seen is the enabled aspect. This state is defined by the method `isNameEnabled`.

Each aspect has a name. The enabled aspect has the name "enabled" whereas the value aspect has the empty String as name. In general, the state of the aspect "aspect" for property "property" is determined by the method `is/get<Property><Aspect>` and `set<Property><Aspect>`.

Aspects can also apply to the whole PMO if it is also bound to a UI component. In this case, the property name is the empty string.

.Aspect on PMO class
[source,java]
----
include::{source-dir}/org/linkki/doc/dynamic/PartnerSectionPmo.java[tags=aspectOnClass]
----

[[embedded-aspects]]
==== Commonly Embedded Aspects

Some aspects are so important or commonly used that they are directly packaged with the <<ui-element, UI annotation>>. Many of those aspects offer configurations that can be set by attributes in the annotation. Most frequently, the attributes share the name of the aspect itself, e.g. `@UITextField(enabled = ...)` in case of the enabled aspect. 

Below are the commonly embedded aspects.

[[label]]
===== Label
Usually there is a label text for each UI element, that describes the element. The content of the label is defined by this attribute.

Exceptions to this are elements whose main feature is their text, such as <<ui-button, buttons>>, <<ui-checkbox, checkboxes>> and <<ui-link, links>>. These UI elements usually do not need a preceding label. Instead, the description of a button is displayed on the button itself, the description of a link is displayed as the link text, while the description of the checkbox is commonly displayed at the right of the checkbox. This kind of describing element can be configured with the property `caption` in those annotations. Buttons, links and checkboxes can still be configured with a label additionally by overwriting the `label` property.

If no label/caption is set, the default value `"derived.by.linkki"` kicks in and *linkki* uses the default as determined by the <<property-dispatcher, PropertyDispatchers>> (usually the capitalized property name) as label/caption.

The label is used as the column caption in <<ui-tables, tables>>.

NOTE: If an independent label is needed, the UI element <<ui-label, UILabel>> can be used.

[[enabled]]
===== Enabled
The property `enabled` controls whether a component is enabled or disabled. The following configuration options are available:

[cols="1,8"]
.EnabledType
|===
|`ENABLED`  |The content of the element is modifiable in the UI (*default*)
|`DISABLED` |The content of the element is not modifiable in the UI
|`DYNAMIC`  |Whether the content is modifiable is controlled by the return value of the method `boolean is<PropertyName>Enabled()`
|===

NOTE: Some components like <<ui-label, UILabel>> and <<ui-link, UILink>> do not offer these options and are always enabled.

[[visible]]
===== Visible
The property `visible` controls whether the component is visible. There are the following configuration options:

[cols="1,7"]
.VisibleType
|===
|`VISIBLE`   |The UI element is visible (*default*)
|`INVISIBLE` |The UI element is invisible
|`DYNAMIC`   |Whether the UI element is visible is controlled by the return value of the method `boolean is<PropertyName>Visible()`
|=== 

[[required]]
===== Required
The property `required` visually highlights required fields. The following configuration options are available:

[cols="1,3"]
.RequiredType
|===
|`REQUIRED`              |The UI element requires input (a value must be entered/selected)
|`REQUIRED_IF_ENABLED`   |The UI element requires input if it is `enabled`
|`NOT_REQUIRED`          |Input in the UI element is optional (*default*)
|`DYNAMIC`               |Whether the element requires input is controlled by the return value of the method `boolean is<PropertyName>Required()`
|===

NOTE: <<ui-label, UILabels>>, <<ui-link, UILinks>> and <<ui-button, UIButtons>> do not offer these options and are never required.

WARNING: Fields marked as `required` are only visually highlighted. *No* validation is performed.

[[standalone-aspects]]
==== Standalone Aspect Annotations

Aspects can also be represented by a separate annotation. In this case, those annotations follow the naming convention `@Bind[AspectName]`. A standalone aspect annotation can be added to an annotated PMO property. Some standalone aspect annotation can also be added to an annotated PMO class itself. In the case of binding using the `@Bind` annotation, `@Bind[AspectName]` must be written directly in the field annotated with `@Bind`. Several frequently used aspects are packaged with *linkki* as listed below. It is also very easy to create additional <<creating-aspects, custom aspect annotations>>. 

[options="header"]
|===
| Standalone Annotation | Description
| `<<tooltips, @BindTooltip>>` | `Tooltip handling, using default TooltipType.AUTO`
| `<<bind-read-only, @BindReadOnly>>` | `Bind a component's read-only property. Exclusive to Components of type HasValue`
| `<<bind-read-only-behavior, @BindReadOnlyBehavior>>` | `Automatically change enabled or visible behavior when in read-only mode.`
| `<<bind-visible, @BindVisible>>` | `Visiblity handling, using default VisibleType.DYNAMIC`
| `<<bind-style-names, @BindStyleNames>>` | `Provide style class names for a component`
| `<<bind-caption, @BindCaption>>` | `Caption handling, using default CaptionType.AUTO`
| `<<bind-icon, @BindIcon>>` | `Icon handling, using default IconType.AUTO`
| `<<suffix, @BindSuffix>>` | `Suffix handling, using default SuffixType.AUTO`
| `<<placeholder, @BindPlaceholder>>`| `Placeholder handling, using default PlaceholderType.AUTO`
| `<<autofocus, @BindAutoFocus>>`| `Bind the autofocus property of a UI element.`
|`<<variant-names, @BindVariantNames>>`| `Bind variant theme to a UI element or PMO class.`
|===

[[tooltips]]
===== Tooltips

For displaying tooltips on UI elements *linkki* provides the annotation `@BindTooltip`. 

The `@BindTooltip` annotation has two properties:

* <<tooltip-text, `value: String`>>
* <<tooltip-type, `tooltipType: TooltipType`>>

[[tooltip-text]]
Value::
This is the text displayed on <<tooltip-type, `TooltipType.STATIC`>>. Its default value is an empty string (`""`).

[[tooltip-type]]
TooltipType::
The following configuration options are available for `TooltipType`:
+
[cols="1,9"]
.TooltipType
|===
|`AUTO`     |The text of the tooltip is read from the attribute `value` if it is not empty, otherwise it reacts like `DYNAMIC` (*default*)
|`STATIC`   |The text of the tooltip is read from the attribute `value`
|`DYNAMIC`  |The text of the tooltip is determined by the return value of the method `String get<PropertyName>Tooltip()`. The `value` is ignored.
|===

TIP: Tooltips can only be added to <<ui-field, fields>> and <<ui-button, buttons>>.

[source,java]
----
include::{source-dir-playground}/org/linkki/samples/playground/binding/pmo/ContactRowPmo.java[tags=contactRowPmo-buttonBinding]
----

[[bind-read-only]]
===== Bind Read-Only State

To change a component's read-only behavior, *linkki* provides the annotation `@BindReadOnly`. This annotation can be used in combination with  @Bind or UI-annotations.

IMPORTANT: The `@BindReadOnly` annotation is evaluated after `@Bind` or `@UI-annotations` which might already have set a read-only state.

TIP: This annotation should be used only in exceptional cases, since most of the behavior is better controlled by a <<cross-sectional-binding, PropertyBehavior>>.

The `@BindReadOnly` Annotation has only one property, `ReadOnlyType`. Per default, `ReadOnlyType#ALWAYS` is selected. Following `ReadOnlyTypes` are available:

[cols="1,9"]
.ReadOnlyType
|===
|`ALWAYS`   |The component is always read-only (*default*).
|`DYNAMIC`  |The read-only behavior of the component is determined by the return value of the method `is<PropertyName>ReadOnly()`.
|`DERIVED`  |The component is read-only if no setter method exists or the property dispatcher returns read-only for this property.
|===

TIP: If a component is supposed to be writable even though the rest of the UI is in read-only-mode, use <<bind-read-only-behavior,`@BindReadOnlyBehavior`>> with value `ACTIVE`, e.g. an input field to filter the content of a table.

[[bind-read-only-behavior]]
===== Bind Read-Only Behavior

`@BindReadOnlyBehavior` changes a component's behaviour if it is set to read-only. The read-only status is determined by the <<property-dispatcher, property-dispatcher-chain>>. There is no need to define additional methods as is usually the case with dynamic aspect definitions. 

The aspect has a value of type `ReadOnlyBehaviorType` with the following options available: 

[cols="1,9"]
.ReadOnlyBehaviorType
|===
|`INVISIBLE` |Component is invisible in read-only mode. This type is the default value.
|`DISABLED` |Component is visible but disabled in read-only mode.
|`WRITABLE` |Component remains writable in read-only mode.
|`INVISIBLE_IF_WRITABLE` |Component is invisible in writable mode.
|===

TIP: `INVISIBLE` and `DISABLED` are especially useful for buttons as buttons do not have a read-only mode. The type `WRITABLE` is useful for components which do not change data like an input field that is used to filter the content in the user interface.

TIP: `INVISIBLE_IF_WRITABLE` can be used for buttons which should only be visible in read-only mode.

IMPORTANT: `INVISIBLE`, `DISABLED`, `INVISIBLE_IF_WRITABLE` are only supported for buttons yet. `WRITABLE` can only be used on UI elements which implement `HasValue`.

[[bind-visible]]
===== Bind Visible

`@BindVisible` changes a component's visibility from the PMO by invoking a method named `is[PropertyName]Visible()`.

The aspect has a default value of type `VisibiltyType` with the option `DYNAMIC`. Using this annotation, it is no longer necessary to specify the `visible` property with `VisibleType.DYNAMIC` in components, e.g. `@UILabel`.

[[bind-style-names]]
===== Style Names

Vaadin components get rendered as HTML and styled via CSS. Using the `@BindStyleNames` annotation custom style names can be bound to a component in addition to those provided by Vaadin.

A single style name can be provided as the annotation's value (`@BindStyleNames("foo")`) as well as an array of multiple style names (`@BindStyleNames({"bar", "baz"})`).

The value can also be omitted, leading to dynamic resolution via a `get<Property>StyleNames()` method that may return a `String` or any `Collection<String>`.

NOTE: This aspect is an inherited aspect if it is declared on a class. Style names defined in the inheritance hierarchy are all added to the component.

[[bind-combo-box-item-style]]
===== Combo Box Item Style

With the `@BindComboBoxItemStyle` annotation it is possible to style the items in a combo box popup menu. The annotation can only be used in conjunction with the annotation <<ui-combobox, @UIComboBox>>.

The CSS style names can be specified directly in the annotation and then apply to all items.

Alternatively, the annotation can be specified without style names, in which case a method named `get<Property>ItemStyle()` is called with return type `Function<TYPE, String>`. The type `TYPE` must correspond to the type of the items in the combo box. The function is called for each item in the combo box. This makes it possible to define different styles for individual items.

[[ui-combobox-dynamicCaption]]
===== @BindComboBoxDynamicCaption
By default, the caption of an item is only updated if the item itself changes. If the caption of an item can change without the item itself being changed, the combo box should be additionally be annotated with `@BindComboBoxDynamicCaption`. This annotation makes sure that all items are updated including their caption upon updates.

WARNING: The update of all items can be costly, especially if the combo box contains a large number of items. 

[[bind-caption]]
===== Caption

For sections and applicable fields(e.g. <<ui-checkbox,`UICheckbox`>>, <<ui-button,`UIButton`>>), the caption can be set with the separate `@BindCaption` annotation. 

The `@BindCaption` annotation has two properties:

* <<caption-text, `value: String`>>
* <<caption-type, `captionType: CaptionType`>>

[[caption-text]]
Value::
This is the text displayed on <<caption-type, `CaptionType.STATIC`>>. Its default value is an empty string (`""`).

[[caption-type]]
CaptionType::
The following configuration options are available for `CaptionType`:

[cols="1,9"]
.CaptionType
|===
|`AUTO`     |Reacts as `DYNAMIC` if value is empty or `STATIC` if it is not empty (*default*)
|`STATIC`   |The caption is read from the attribute `value`
|`DYNAMIC`  |The caption is determined by the return value of the method `String get<PropertyName>Caption()`. The `value` is ignored.
|`NONE`     |Explicitly set the caption to `null`
|===

[[bind-icon]]
===== Icon

UI elements such as <<ui-button, `@UIButton`>> or <<ui-link, `@UILink`>> can have an icon that is shown with the component's caption. This can be set with the `@BindIcon` annotation.

The `@BindIcon` annotation has two properties:

* <<icon-value, `value: String`>>  
* <<icon-type, `iconType: IconTypeType`>>

[[icon-value]]
Value::
This is the icon displayed on <<icon-type, `IconType.STATIC`>>. Its default value is a smiley that should alarm the user in case of unintentional usage.

[[icon-type]]
IconType::
The following configuration options are available for `IconType`:

[cols="1,9"]
.IconType
|===
|`AUTO`     |Reacts as `STATIC` if icon is specified or `DYNAMIC` if not (*default*)
|`STATIC`   |The icon is read from the attribute `value`
|`DYNAMIC`  |The icon is determined by the return value of the method `Resource get<PropertyName>Icon()`. The `value` is ignored. 
|=== 

TIP: The class `VaadinIcon` contains many Icons for easy use. The Vaadin documentation includes a https://vaadin.com/components/vaadin-icons/java-examples#all-icons[reference page listing all available icons] as well as documentation how to https://vaadin.com/docs/latest/flow/application/resources#icons[Icons].

IMPORTANT: Since annotations do not support a `null` value and `VaadinIcon` do not have a "NO_ICON" we cannot really specify "no icon" to automatically use a dynamic one. Hence we decided to use a quite uncommon icon (NATIVE_BUTTON) as default. If you really need exactly this icon, use `iconType=STATIC` explicitly.

[[suffix]]
===== Suffix

The annotation `@BindSuffix` can be used to add a suffix on UI elements.

TIP: This can be useful to display units or currencies.

The `@BindSuffix` annotation has two properties:

* <<suffix-text, `value: String`>>
* <<suffix-type, `suffixType: SuffixType`>>

[[suffix-text]]
Value::
This is the content of the suffix that is set at the end of a UI element.
[[suffix-type]]
SuffixType::
The following configuration options are available for `SuffixType`:

[cols="1,9"]
.SuffixType
|===
|`AUTO`     |The text of the suffix is read from the attribute `value` if it is not empty, otherwise it reacts like `DYNAMIC` (*default*)
|`STATIC`   |The text of the suffix is read from the attribute `value`
|`DYNAMIC`  |The text of the suffix is determined by the return value of the method `String get<PropertyName>Suffix()`. The `value` is ignored.
|===

TIP:  BindSuffix can add a suffix to UI elements which implement the `HasPrefixAndSuffix` interface. Common UI elements which support `@BindSuffix` are `@UIIntegerField`, `@UIDoubleField`, `@UIDecimalField`, `@UITextField`, `@UITextArea`, `@UICustomField`.

[[placeholder]]
===== Placeholder

The annotation `@BindPlaceholder` can be used to display a placeholder on UI elements.

The `@BindPlaceholder` annotation has two properties:

* <<placeholder-text, `value: String`>>
* <<placeholder-type, `placeholderType: PlaceholderType`>>

[[placeholder-text]]
Value::
This is the content that is displayed in a UI element when it is empty.

[[placeholder-type]]
PlaceholderType::
The following configuration options are available for `PlaceholderType`:

[cols="1,9"]
.PlaceholderType
|===
|`AUTO`     |The text of the placeholder is read from the attribute `value` if it is not empty, otherwise it reacts like `DYNAMIC` (*default*)
|`STATIC`   |The text of the placeholder is read from the attribute `value`
|`DYNAMIC`  |The text of the placeholder is determined by the return value of the method `String get<PropertyName>Placeholder()`. The `value` is ignored.
|===

[[placeholder-table-pmo]]
The `@BindPlaceholder` annotation can also be used on table PMOs providing a placeholder text that is shown in case the table has no items. Table header and footer will also be hidden.

NOTE: This aspect is an inherited aspect. If a class is annotated with `@BindPlaceholder`, all subclasses will hide their tables using the declared annotation in their super class. It is not possible for subclasses to override this behavior.

.`@BindPlaceholder` on table PMO
[source,java]
----
include::{source-dir-playground}/org/linkki/samples/playground/table/SimplePlaygroundTablePmo.java[tags=bindPlaceholder-tablePmo]
----

TIP: `@BindPlaceholder(value = "", placeholderType = PlaceholderType.STATIC)` will hide empty tables without showing any replacement text. When using `@BindPlaceholder` as annotation only, providing mandatory `getPlaceholder()`-Method and returning empty `String` will do the same.

[[autofocus]]
===== AutoFocus

The annotation `@BindAutoFocus` can be used to set the https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus[autofocus] attribute on a UI element.

IMPORTANT: This annotation should only be used on one UI element per page/dialog. The target element must be visible and editable. This annotation does not work with `@UIRadioButtons`.

NOTE: When used on a `@UIDateTimeField`, the date input field will be autofocused.

.`@BindAutoFocus` on a text field
[source,java]
----
include::{source-dir-playground}/org/linkki/samples/playground/ts/aspects/BindAutoFocusPmo.java[tags=bindAutoFocus]
----

TIP: BindAutoFocus can set the `autofocus` property on UI elements which implement the `HasValue` and `HasElement` interfaces. Common UI elements which support `@BindAutoFocus` are `@UIIntegerField`, `@UIDoubleField`, `@UIDecimalField`, `@UITextField`, `@UITextArea`, `@UICustomField`, `@UIDateField`, `@UIDateTimeField`, `@UICheckBox` and `@UIComboBox`.

[[variant-names]]
===== Variant names

Vaadin components get rendered as HTML and styled via CSS. The `@BindVariantNames` annotation can be used to add specific Vaadin variants to components implementing the `HasTheme` interface.
It is possible to provide a single variant name (`@BindVariantNames("no-border")`) or an array of variant names (`@BindVariantNames({"no-row-borders", "compact"})`) as the annotation's value.

.`@BindVariantNames` on TablePmo
[source,java]
----
include::{source-dir-playground}/org/linkki/samples/playground/ts/aspects/BindVariantNamesTables.java[tags=bindVariantNames]
----

