:jbake-title: Project Setup
:jbake-type: section
:jbake-status: published

:base-dir: ../../../../../../vaadin8/samples/getting-started
:tree-sample-dir: ../../../../../../vaadin8/samples/tree-table
:sample-parent-dir: ../../../../../../vaadin8/samples

[[project-setup]]
=== Project Setup

You can either add the required dependencies to an existing project or use one of the <<maven-archetypes,Maven archetypes>> to get started.

==== Prerequisites

To start this project, you need

 * Java 8
 * your favorite Java IDE
 * Maven
 * a modern browser

==== Maven

Apart from *linkki* we require Vaadin as dependency:

[source,xml]
----
include::{sample-parent-dir}/pom.xml[tags=vaadin]
----

And the matching UI framework dependent *linkki* module:

[source,xml]
----
include::{sample-parent-dir}/pom.xml[tags=linkki-core-vaadin8]
----

In the above example, we are creating a web application that is packaged as `war`, as it is needed for the <<linkki-example, *linkki* example>>.

[[maven-archetypes]]
==== Maven Archetypes

*linkki* can be used for a plain Vaadin web application, with Spring Boot or with CDI. For each of those options, there is a matching Maven archetype that creates a new project with all necessary dependencies and some sample code to get started. They can be created from a command line:

[source,subs="verbatim,attributes"]
.Plain *linkki*
----
mvn archetype:generate -DarchetypeGroupId=org.linkki-framework.archetypes -DarchetypeArtifactId=linkki-archetype-plain-application-vaadin8 -DarchetypeVersion={dversion}
----

The resulting application can be deployed to your application server of choice or simply started with `mvn clean package org.eclipse.jetty:jetty-maven-plugin:run`, where it can be viewed at `http://localhost:8080/main`.

[source,subs="verbatim,attributes"]
.*linkki* with CDI
----
mvn archetype:generate -DarchetypeGroupId=org.linkki-framework.archetypes -DarchetypeArtifactId=linkki-archetype-cdi-application-vaadin8 -DarchetypeVersion={dversion}
----

The resulting application can be deployed to your Java Enterprise Edition 7+ server of choice or simply started with `mvn clean package org.apache.tomee.maven:tomee-maven-plugin:run`, where it can be viewed at `http://localhost:8080/<yourArtifactId>`.

[source,subs="verbatim,attributes"]
.*linkki* with Spring Boot
----
mvn archetype:generate -DarchetypeGroupId=org.linkki-framework.archetypes -DarchetypeArtifactId=linkki-archetype-spring-application-vaadin8 -DarchetypeVersion={dversion}
----

The resulting application can be started with `java -jar target/*.war` and be viewed at `http://localhost:8080/`.