:jbake-title: Latest
:jbake-type: section
:jbake-status: published
:jbake-order: 0

// NO :source-dir: HERE, BECAUSE N&N NEEDS TO SHOW CODE AT IT'S TIME OF ORIGIN, NOT LINK TO CURRENT CODE
:images-folder-name: 01_newnoteworthy

++++
<style>
// Should be created as a separate CSS file for a custom jbake-type

.api-change > h5:after,
.api-change > h4:after,
.api-change > h3:after {
  content: 'api-change';
  color: white;
	margin-left: 1em;
	font-weight: bold;
	border-radius: 2px;
	background: #009fe3;
	padding: .3em 1em;
	font-size: .8em;
	box-shadow: 1px 1px 5px rgba(0,0,0,0.1);
}

.sect3 {
	margin-bottom: 4em;
}
</style>
++++

=== {dversion}

[role="api-change"]
===== OKCancelDialog

The `openOkCancelDialog(String, Object, Handler)` method in `PmoBasedDialogFactory` is deprecated as the method had different argument order compared to newOkCancelDialog() method. Use `openOkCancelDialog(String, Handler, Handler, Object...)` instead. It creates a new `OkCancelDialog` based on multiple PMOs and opens the dialog.

To mirror the corresponding `newOkDialog` following methods are also introduced in `PmoBasedDialogFactory`.

[options="header"]
|===
| New Methods | Description
|`openOkDialog(String, Object...)` | creates a new `OkCancelDialog` and opens the dialog.
|`openOkCancelDialog(String, Handler , Object...)` | creates a new `OkCancelDialog` based on multiple PMOs with okHandler and opens the dialog
|===

==== New method in `BindingManager` to create a `BindingContext` with a `PropertyBehaviorProvider`

For a while now, `BindingContexts` can accept a `PropertyBehaviorProvider` that defines which behaviors are to be used for all bindings in the context. However, `BindingManager` does not directly offer any support for `PropertyBehaviors` when creating new `BindingContexts` yet. In the default implementation `DefaultBindingManager`, the constructor accepts a `PropertyBehaviorProvider` that is used for all new `BindingContexts`. No individual choices can be made.

In the new linkki version, `BindingManager` is extended with two new methods `createContext(Class, PropertyBehaviorProvider)` and `createContext(String, PropertyBehaviorProvider)`. These methods enables the caller to create a `BindingContext` using the specific behaviors that are passed to the method. The section "<<property-behavior-binding-manager, Using PropertyBehaviors with a BindingManager>>" in chapter "architecture" of the documentation contains further information about these methods.

If you are creating an `AbstractPage` which should use a custom `PropertyBehaviorProvider`, you can create a new `BindingContext` using the new methods, and use this context in the method `getBindingContext()`.

[role="api-change"]
===== `startNewContext` deprecated
The `BindingManager`'s `startNewContext` method has been deprecated, as it is no longer necessary to explicitly start a context. When `getContext` is called, a new context is created as necessary. Existing calls can be refactored with link:../migration_scripts/0.9.20190528_to_latest/migrate.sed[0.9.20190528_to_latest/migrate.sed].

===== `@BindCaption`
Section and field captions can now be bound via <<bind-caption,`@BindCaption`>>. In preparation for this, the `AbstractSection` was refactored to allow setting(and removing) a caption after construction.

===== Bugfixes

* When using a PMO property with <<dynamicfield,dynamic fields>> with different bound model attributes, every field was bound to the first annotation's model attribute.
