:jbake-title: Latest
:jbake-type: section
:jbake-status: published
:jbake-order: 0

// NO :source-dir: HERE, BECAUSE N&N NEEDS TO SHOW CODE AT IT'S TIME OF ORIGIN, NOT LINK TO CURRENT CODE
:images-folder-name: 01_newnoteworthy

++++
<style>
// Should be created as a separate CSS file for a custom jbake-type

.api-change > h5:after,
.api-change > h4:after,
.api-change > h3:after {
  content: 'api-change';
  color: white;
	margin-left: 1em;
	font-weight: bold;
	border-radius: 2px;
	background: #009fe3;
	padding: .3em 1em;
	font-size: .8em;
	box-shadow: 1px 1px 5px rgba(0,0,0,0.1);
}

.sect3 {
	margin-bottom: 4em;
}

details > summary {
	display: list-item;
}

details > div {
  padding-left: 1em;
  margin-left: .2em;
  border-left: 3px #eee solid;
}
</style>
++++

=== {dversion}

[role="api-change"]
===== OKCancelDialog

The `openOkCancelDialog(String, Object, Handler)` method in `PmoBasedDialogFactory` is deprecated as the method had different argument order compared to newOkCancelDialog() method. Use `openOkCancelDialog(String, Handler, Handler, Object...)` instead. It creates a new `OkCancelDialog` based on multiple PMOs and opens the dialog.

To mirror the corresponding `newOkDialog` following methods are also introduced in `PmoBasedDialogFactory`.

[options="header"]
|===
| New Methods | Description
|`openOkDialog(String, Object...)` | creates a new `OkCancelDialog` and opens the dialog.
|`openOkCancelDialog(String, Handler , Object...)` | creates a new `OkCancelDialog` based on multiple PMOs with okHandler and opens the dialog
|===
==== Passing a `PropertyBehaviorProvider` to a `BindingContext`
The `DefaultBindingManager` already has a `PropertyBehaviorProvider` passed in its constructor which it uses to create new `BindingContexts`. A different behavior in one context within the same manager was not possible. Now, the methods `createContext(Class/String, PropertyBehaviorProvider)` can be used to create a new context with a custom behavior. They throw `IllegalArgumentExceptions` if called with an existing context's class/name.

The previously introduced `getContext` methods can then be used to access the context created with `createContext` later without the need to keep a reference to the `PropertyBehaviorProvider` and create a new context with the default behavior if none was explicitly created.

If the default behaviors should not be replaced but only extended, `DefaultBindingManager.getDefaultBehaviorProvider()` allows access to the  `PropertyBehaviorProvider` from which a new one can be created with `PropertyBehaviorProvider.append(PropertyBehavior...)`.

.Example use of PropertyBehaviorProvider.append
[source,java]
----
        bindingManager.createContext(myPmo.getClass(),
                                     bindingManager.getDefaultBehaviorProvider()
                                             .append(PropertyBehavior.readOnly()));
----
[role="api-change"]
===== `startNewContext` deprecated
The `BindingManager`'s `startNewContext` method has been deprecated, as it is no longer necessary to explicitly start a context. When `getContext` is called, a new context is created as necessary. Existing calls can be refactored with link:../migration_scripts/0.9.20190528_to_latest/migrate.sed[0.9.20190528_to_latest/migrate.sed].

===== Bugfixes

* When using a PMO property with <<dynamicfield,dynamic fields>> with different bound model attributes, every field was bound to the first annotation's model attribute.