:jbake-type: referenced
:jbake-status: referenced
:jbake-order: 0

// NO :source-dir: HERE, BECAUSE N&N NEEDS TO SHOW CODE AT IT'S TIME OF ORIGIN, NOT LINK TO CURRENT CODE
:images-folder-name: 01_newnoteworthy

=== 1.2.0

==== Buttons and Arbitrary UI Elements in Section Headers

Using the annotation <<section-header-annotation,@SectionHeader>>, any UI element can now be added to a section's header instead of its content area. This should be used instead of a button PMO returned from `PresentationModelObject#getEditButtonPmo()`.

==== Radio Buttons

Vaadin's radio button group, previously only used as an <<custom-ui-element-annotation,example how to create a custom UI element>>, is now also a part of linkki for Vaadin 8 with the <<ui-radiobutton,`@UIRadioButtons`>> annotation.

==== Incubator Project & Nested PMOs

The new incubator module offers access to features in development, such as <<nested-pmos,nested PMOs>>.

==== APT Exception Handling for Aspect Definitions

Exceptions thrown when APT calls the `createAspect` method of aspect definition no longer abort the build. Instead, an <<apt-compiler-options,ASPECT_CREATION_FAILED warning>> is now emitted.