:jbake-type: referenced
:jbake-status: referenced
:jbake-order: 0

// NO :source-dir: HERE, BECAUSE N&N NEEDS TO SHOW CODE AT IT'S TIME OF ORIGIN, NOT LINK TO CURRENT CODE
:images-folder-name: 01_newnoteworthy

=== 1.2.0

==== Buttons and Arbitrary UI Elements in Section Headers

Using the annotation <<section-header-annotation,@SectionHeader>>, any UI element can now be added to a section's header instead of its content area. This should be used instead of a button PMO returned from `PresentationModelObject#getEditButtonPmo()`.

==== Radio Buttons

Vaadin's radio button group, previously only used as an <<custom-ui-element-annotation,example how to create a custom UI element>>, is now also a part of linkki for Vaadin 8 with the <<ui-radiobutton,`@UIRadioButtons`>> annotation.

==== SidebarLayout/SidebarSheet

The `SidebarLayout` got a `SelectionListener` to get an event when the selected sidebar sheet changes. To identify the selected sidebar sheet
for example when the selected sheet is referenced by a URL parameter, the sidebar sheets now have an optional ID. The ID is derived from name if it
was not specified explicitly but it is recommended to make it explicit.

The `UiUpdateObserver` in `SidebarSheet` is still the recommended way to trigger an update when the sheet gets selected. This way it remains self-contained (the layout does not need to know how to update the sheet). To make the instantiation more flexible, the `UiUpdateObserver` could now be specified after constructor using a setter.

==== Incubator Project & Nested PMOs

The new incubator module offers access to features in development, such as <<nested-pmos,nested PMOs>>.

==== APT Exception Handling for Aspect Definitions

Exceptions thrown when APT calls the `createAspect` method of aspect definition no longer abort the build. Instead, an <<apt-compiler-options,ASPECT_CREATION_FAILED warning>> is now emitted.

[role="api-change"]
==== ComponentWrapper now Stores Reference to Binding

The new method `ComponentWrapper.registerBinding(Binding binding)` creates a strong reference from a component to their `Binding`.
The `BindingContext` is therefore able to keep only weak references to all `Bindings`.
Likewise, the method `BindingContext.add(Binding binding)` has been deprecated and replaced with the new signature `BindingContext.add(Binding binding, ComponentWrapper componentWrapper)`.

==== New Widgetset Allows Flexible Date Entry

*linkki* now includes its own <<widgetset>> that offers a more flexible <<ui-datefield,date entry field>>. You can switch to it with

[source,java]
----
@Widgetset("org.linkki.core.vaadin.component.LinkkiWidgetset")
----

==== Update Vaadin to 8.10.4

linkki now uses Vaadin version 8.10.4 to include the latest bug fixes and patches.