:jbake-type: referenced
:jbake-status: referenced
:jbake-order: 0

// NO :source-dir: HERE, BECAUSE N&N NEEDS TO SHOW CODE AT IT'S TIME OF ORIGIN, NOT LINK TO CURRENT CODE
:images-folder-name: 00_releasenotes

=== Version 2.7.0

==== New features and improvements

===== Dependency Updates

The following versions have been updated:

[cols="a,a"]
|===
| Faktor-IPS                    | 24.7.2.release
| Vaadin                        | 24.4.12
| Spring Boot                   | 3.3.4
|===

The new Vaadin version brings some notable changes that affect linkki applications:

Selecting an invalid index in `LinkkiTabLayout`::
When selecting an invalid index in a `LinkkiTabLayout` there is no exception thrown anymore.
Instead, the tab layout reverts to the previously selected valid index. For more information, see link:https://github.com/vaadin/flow-components/pull/6543[here].

New properties in `LumoUtility` and `LumoConstants`::
In `LumoUtility` new properties have been added. The corresponding properties have also been added to `LumoConstants`. For more information, see link:https://github.com/vaadin/flow-components/pull/6410[here].

// https://jira.convista.com/browse/LIN-3417
===== New annotation for Checkbox Group: `@UICheckboxes`
A new UI component, `@UICheckboxes`, is now available, providing a way to create a checkbox group for related binary choices. For more information, see <<ui-checkboxes, here>>.

// https://jira.convista.com/browse/LIN-3629
===== New annotation for Number Field Group: `@UILongField`
A new UI component, `@UILongField`, is now available, providing a way to accept a very long number. For more information, see <<ui-numberfield, here>>.

// https://jira.convista.com/browse/LIN-3884
===== Testbench extension: support for table placeholder
The new page object `LinkkiGridElement` adds support to retrieve the placeholder text of a table. It can be used instead of `GridElement`, e.g. `$(LinkkiGridElement.class)`.

// https://jira.convista.com/browse/LIN-3970
===== Automatically focus first applicable element in combobox

If a character or word is entered into a combobox and there is only one matching element, then this element gets selected automatically.

Example::
A combobox has the values UP, DOWN, LEFT, RIGHT.
+
If the user enters 'u', the entry UP is selected automatically.
+
If the user enters 't', there are two possible matches (LEFT and RIGHT) and therefore no entry is selected automatically.

==== Bugfixes

// https://jira.convista.com/browse/LIN-3880
* Card sections theme now only applies to dialogs if the theme is explicitly set on the dialog itself or a child layout.
+
// https://jira.convista.com/browse/LIN-3034
* The disabled and readonly style of radio buttons and checkboxes has been harmonised to follow the linkki style guidelines.
+
// https://jira.convista.com/browse/LIN-3868
* `DefaultCaptionProvider` now takes the provided locale into account and translates the captions accordingly.
+
//https://jira.convista.com/browse/LIN-3802
* The <<gitignore,recommended .gitignore>> file is now added in generated archetype projects.
+
//https://jira.convista.com/browse/LIN-3899
* Components within a form layout that are required and have an empty/ blank label do not scroll anymore.
+
//https://jira.convista.com/browse/LIN-2152
* `@UIDecimalField` now handles very large numbers without unwanted rounding.
+
//https://jira.convista.com/browse/LIN-3879
* Previously, setting the value to `null` in `@UIRadioButtons` failed to check the appropriate radio button.
Now, selecting `null` correctly checks the "Not specified" radio button, ensuring proper representation.
+
[WARNING]
====
With this bug fix, the converter must now be able to handle null-valued presentation values. Although this was already part of the `Converter` contract, it can now lead to an exception in `ValueAspectDefinition`.
====
