:jbake-type: referenced
:jbake-status: referenced
:jbake-order: 0

// NO :source-dir: HERE, BECAUSE N&N NEEDS TO SHOW CODE AT IT'S TIME OF ORIGIN, NOT LINK TO CURRENT CODE
:images-folder-name: 00_releasenotes

=== Version 2.7.0

==== New features and improvements

// ===== Dependency Updates
//
// The following versions have been updated:
//
// [cols="a,a"]
// |===
// | Faktor-IPS                | 24.7.1.release
// | Vaadin                    | 24.4.3
// | Spring Boot               | 3.3.1
// |===

// https://jira.convista.com/browse/LIN-3417
===== New annotation for Checkbox Group: `@UICheckboxes`
A new UI component, `@UICheckboxes`, is now available, providing a way to create a checkbox group for related binary choices. For more information, see <<ui-checkboxes, here>>.

==== Bugfixes

// https://jira.convista.com/browse/LIN-3880
Card section theme for dialogs::
Card sections theme now only applies to dialogs if the theme is explicitly set on the dialog itself or a child layout.

// https://jira.convista.com/browse/LIN-3034
Disabled and readonly style for radio button and checkbox::
The disabled and readonly style of radio buttons and checkboxes has been harmonised to follow the linkki style guidelines.

// https://jira.convista.com/browse/LIN-3868
`DefaultCaptionProvider` uses the provided `Locale`::
If the provided `Locale` is `null`, it defaults to `UiFramework.getLocale()`.
It does not ignore the provided `Locale` for `Boolean` captions anymore.
