:jbake-type: referenced
:jbake-status: referenced
:jbake-order: 0

// NO :source-dir: HERE, BECAUSE N&N NEEDS TO SHOW CODE AT IT'S TIME OF ORIGIN, NOT LINK TO CURRENT CODE
:images-folder-name: 00_releasenotes

=== Version 2.7.0

==== New features and improvements

===== Dependency Updates

The following versions have been updated:

[cols="a,a"]
|===
| Faktor-IPS                    | 25.1.0.release
| Vaadin                        | 24.5.8
| Spring Boot                   | 3.4.0
|===

The new Vaadin version brings some notable changes that affect linkki applications:

Selecting an invalid index in `LinkkiTabLayout`::
When selecting an invalid index in a `LinkkiTabLayout` there is no exception thrown anymore.
Instead, the tab layout reverts to the previously selected valid index.
For more information, see link:https://github.com/vaadin/flow-components/pull/6543[here].

New properties in `LumoUtility`::
In `LumoUtility` new properties have been added.
For more information, see link:https://github.com/vaadin/flow-components/pull/6410[here].

// https://jira.convista.com/browse/LIN-3417
===== New annotation for Checkbox Group: `@UICheckboxes`

A new UI component, `@UICheckboxes`, is now available, providing a way to create a checkbox group for related binary choices.
For more information, see <<ui-checkboxes, here>>.

// https://jira.convista.com/browse/LIN-3629
===== New annotation for Number Field: `@UILongField`

A new UI component, `@UILongField`, is now available, providing a way to accept a very long number.
For more information, see <<ui-numberfield, here>>.

// https://jira.convista.com/browse/LIN-3884
===== Testbench extension: support for table placeholder

The new page object `LinkkiGridElement` adds support to retrieve the placeholder text of a table.
It can be used instead of `GridElement`, e.g. `$(LinkkiGridElement.class)`.

// https://jira.convista.com/browse/LIN-3970
===== Automatically focus first applicable element in combobox

If a character or word is entered into a combobox and there is only one matching element, then this element gets selected automatically.

Example::
A combobox has the values UP, DOWN, LEFT, RIGHT.
+
If the user enters 'u', the entry UP is selected automatically.
+
If the user enters 't', there are two possible matches (LEFT and RIGHT) and therefore no entry is selected automatically.

// https://jira.convista.com/browse/LIN-3739
===== `@UILabel` now supports displaying asynchronously loaded values

`UILabel` has been enhanced to handle asynchronous value loading using `CompletableFuture` as return type.
A loading indicator will be displayed until the value is available.
Refer to <<ui-label,UILabel>> documentation for more details.


// https://jira.convista.com/browse/LIN-2690
===== @BindPlaceholder with LinkkiSection

The <<placeholder-linkki-section, @BindPlaceholder>> annotation can now be used on a `@UISection` to set a placeholder text if the section has no child elements or all child elements are invisible.

.@BindPlaceholder on @UISection
[source,java]
----
@BindPlaceholder
@UISection(caption = "@UISection with @BindPlaceholder")
public class SectionWithBindPlaceholder {

    public String getPlaceholder() {
        return "This section is empty";
    }

}
----

The old solution using an extra `UILabel` with the style `LinkkiTheme.Text.TEXT_PLACEHOLDER` is now obsolete and should be replaced as it did not work correctly with different layout options.

.Old solution with UILabel and style LinkkiTheme.Text.TEXT_PLACEHOLDER
[source,java]
----
@UISection(caption = "@UISection with placeholder label")
public class SectionWithPlaceholderLabel {

    @UILabel(position = 10, label = "", styleNames = LinkkiTheme.Text.TEXT_PLACEHOLDER)
    public String getPlaceholder() {
        return "This is a placeholder.";
    }

}
----

NOTE: `LinkkiTheme.Text.TEXT_PLACEHOLDER` has been deprecated and should not be used anymore!
Use `@BindPlaceholder` on `@UISection` instead (see above).

==== New aspect annotation `@BindClosable` for sections

A new aspect annotation, `@BindClosable`, is now available, providing a way to create closable sections with the option to have them initially closed.
For more information, see <<section-bind-closable, here>>.

===== More utilities for Karibu tests

Many useful methods were added to the <<karibu-utils, KaribuUtils>> to make it even easier to write Karibu tests.

// https://jira.convista.com/browse/LIN-3444
===== IDs for exceptions in logs

If an exception occurs in the application, it will be displayed by the configured <<linkki-error-dialog, error handler>> or an <<linkki-error-page, error page>> in case of an exception during navigation. With the default configuration, the exception is now logged with a unique ID that is also displayed in the UI, making it easier to find the exception in the logs. Custom implementation may need to be adapted to be able to make use of this feature.

===== linkki tutorial

The <<linkki-tutorial, linkki tutorial>> is now part of this documentation.

==== Bugfixes

// https://jira.convista.com/browse/LIN-4013
* `LabelComponentWrapper#setLabel()` now calls `HasLabel#setLabel()` if the component is an instance of `HasLabel` instead of setting the HTML property directly.
+
// https://jira.convista.com/browse/LIN-3884
* The items of a table created with `@UITableComponent` are now only fetched asynchronously if the return type is `CompletableFuture`.
The <<ui-table-component, documentation>> is updated accordingly.
+
// https://jira.convista.com/browse/LIN-3880
* Card sections theme now only applies to dialogs if the theme is explicitly set on the dialog itself or a child layout.
+
// https://jira.convista.com/browse/LIN-3034
* The disabled and readonly style of radio buttons and checkboxes has been harmonised to follow the linkki style guidelines.
+
// https://jira.convista.com/browse/LIN-3868
* `DefaultCaptionProvider` now takes the provided locale into account and translates the captions accordingly.
+
//https://jira.convista.com/browse/LIN-3802
* The <<gitignore,recommended .gitignore>> file is now added in generated archetype projects.
+
//https://jira.convista.com/browse/LIN-3899
* Components within a form layout that are required and have an empty/ blank label do not scroll anymore.
+
//https://jira.convista.com/browse/LIN-2152
* `@UIDecimalField` now handles very large numbers without unwanted rounding.
+
//https://jira.convista.com/browse/LIN-3879
* Previously, setting the value to `null` in `@UIRadioButtons` failed to check the appropriate radio button.
Now, selecting `null` correctly checks the "Not specified" radio button, ensuring proper representation.
+
[WARNING]
====
With this bug fix, the converter must now be able to handle null-valued presentation values.
Although this was already part of the `Converter` contract, it can now lead to an exception in `ValueAspectDefinition`.
====
