:jbake-type: referenced
:jbake-status: referenced
:jbake-order: 0

// NO :source-dir: HERE, BECAUSE N&N NEEDS TO SHOW CODE AT IT'S TIME OF ORIGIN, NOT LINK TO CURRENT CODE
:images-folder-name: 00_releasenotes

=== Version 2.7.0

==== New features and improvements

===== Dependency Updates

The following versions have been updated:

[cols="a,a"]
|===
// | Faktor-IPS                | 24.7.1.release
| Vaadin                    | 24.4.4
// | Spring Boot               | 3.3.1
|===

// https://jira.convista.com/browse/LIN-3417
===== New annotation for Checkbox Group: `@UICheckboxes`
A new UI component, `@UICheckboxes`, is now available, providing a way to create a checkbox group for related binary choices. For more information, see <<ui-checkboxes, here>>.

// https://jira.convista.com/browse/LIN-3629
===== New annotation for Number Field Group: `@UILongField`
A new UI component, `@UILongField`, is now available, providing a way to accept a very long number. For more information, see <<ui-numberfield, here>>.

// https://jira.convista.com/browse/LIN-3884
===== Testbench extension: support for table placeholder
The new page object `LinkkiGridElement` adds support to retrieve the placeholder text of a table. It can be used instead of `GridElement`, e.g. `$(LinkkiGridElement.class)`.

==== Bugfixes

// https://jira.convista.com/browse/LIN-3880
Card section theme for dialogs::
Card sections theme now only applies to dialogs if the theme is explicitly set on the dialog itself or a child layout.

// https://jira.convista.com/browse/LIN-3034
Disabled and readonly style for radio button and checkbox::
The disabled and readonly style of radio buttons and checkboxes has been harmonised to follow the linkki style guidelines.

// https://jira.convista.com/browse/LIN-3868
`DefaultCaptionProvider` uses the provided `Locale`::
If the provided `Locale` is `null`, it defaults to `UiFramework.getLocale()`.
It does not ignore the provided `Locale` for `Boolean` captions anymore.

//https://jira.convista.com/browse/LIN-3802
Add default .gitignore in archetype projects::
The <<gitignore,recommended .gitignore>> file is now added in generated archetype projects.

//https://jira.convista.com/browse/LIN-3899
Scrollbar on required components with an empty/ blank label::
Components within a form layout that are required and have an empty/ blank label do not scroll anymore.
The required indicator is always visible at the right upper corner of the label.

//https://jira.convista.com/browse/LIN-2152
Large numbers in `@UIDecimalField`::
`@UIDecimalField` now handles very large numbers without unwanted rounding.

//https://jira.convista.com/browse/LIN-3879
Selecting `null` in `@UIRadioButtons`::
Previously, setting the value to `null` failed to select the appropriate radio button.
Now selecting `null` correctly selects the "Not specified" radio button, ensuring proper representation
of the three-state `Boolean` (`true`/`false`/`null`) or an enum extended by `null` in the UI.