:jbake-title: Release Notes
:jbake-type: chapter
:jbake-tags: release-notes
:jbake-status: published
:jbake-order: 0
// NO :source-dir: HERE, BECAUSE N&N NEEDS TO SHOW CODE AT ITS TIME OF ORIGIN, NOT LINK TO CURRENT CODE
:images-folder-name: 01_releasenotes

== Release Notes

//=== Version 2.9.0

// The release notes contain changes compared to link:https://doc.linkki-framework.org/2.8/00_releasenotes/#_version_2_8_0[version 2.8.0].

=== Alpha {vlinkki}

==== Version Updates

The following versions have been updated:

[cols="a,a,a"]
|===
| Dependency                    | New version       | Previous version
| Vaadin | 24.9.3 (link:https://github.com/vaadin/platform/releases/tag/24.9.3[Release Notes])| 24.9.2
| Spring Boot | 3.5.7 (link:https://github.com/spring-projects/spring-boot/releases/tag/v3.5.7[Release Notes])| 3.5.6
| Junit | 5.14.0 (link:https://docs.junit.org/5.14.0/release-notes/#release-notes-5.14.0[Release Notes])| 5.13.4
|===

==== Bugfixes
// https://jira.convista.com/browse/LIN-4518
* *Testbench Extension: error screenshots before @AfterEach methods* +
Failing UI tests now record an error screenshot before any cleanup is done in @AfterEach methods. +
Before this change, error screenshots were taken after cleanup was done by these methods. This sometimes prevents seeing the actual UI state when the error occurred, e.g. when the cleanup logs out of the application.


=== Alpha 2.9.0-a20251008-01

==== Version Updates

The following versions have been updated:

[cols="a,a,a"]
|===
| Dependency                    | New version       | Previous version

| Vaadin                        | 24.9.2  (link:https://github.com/vaadin/platform/releases/tag/24.9.2[Release Notes])| 24.8.10
|===


=== Alpha 2.9.0-a20251007-01

==== Version Updates

The following versions have been updated:

[cols="a,a,a"]
|===
| Dependency                    | New version       | Previous version

| Vaadin                        | 24.8.10 (link:https://github.com/vaadin/platform/releases/tag/24.8.10[Release Notes]) | 24.8.7
| Faktor-IPS                    | 26.1.0.a20251001-01 (link:https://doc.faktorzehn.org/faktor-ips/26.1-a20251001-01/01_releasenotes/index.html[Release Notes]) | 25.7.1-release
| Spring Boot                   | 3.5.6 (link:https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.5-Release-Notes[Release Notes]) | 3.5.5
| Karibu                        | 2.5.0  | 2.4.2
| commons-lang                  | 3.19.0 | 3.18.0
| commons-io                    | 2.20.0 | 2.18.0
| Logback                       | 1.5.19 | 1.5.18
|===

==== UI Annotations and Aspects
// https://jira.convista.com/browse/LIN-4157
* *BindHelperText* +
A new aspect annotation <<bind-helper-text, @BindHelperText>> has been added to show additional information for a field, e.g., regarding its format requirement or purpose.
// https://jira.convista.com/browse/LIN-4530
* *Clear button for UIDateField, UITimeField and UIDateTimeField* +
Date and time fields now have a clear button to erase the current value.
This helps in situations when it is faster to first erase the former value and then insert a new one.

==== Bugfixes

// https://jira.convista.com/browse/LIN-4561
* Entering a value into a cell inside a table created with `@UITableComponent` and traversing with the tab key no longer results in losing focus.

=== Alpha 2.9.0-a20250909-01

==== Version Updates

The following versions have been updated:

[cols="a,a,a"]
|===
| Dependency                    | New version       | Previous version

| Vaadin                        | 24.8.7 (link:https://github.com/vaadin/platform/releases/tag/24.8.7[Release Notes]) | 24.7.12
|===

The update to Vaadin 24.8.7 brings some notable changes:

* *Upload and download Handling* A new API for file upload and download has been introduced.
Users with custom components for upload or download may need to migrate to the new API.
See the https://vaadin.com/docs/latest/flow/advanced/downloads[Vaadin documentation] for details.
* *HTML Sanitization* The new Vaadin version updates the Jsoup version to 1.20.1 in which the HTML sanitization logic was modified.
Some cases are now sanitized differently, for example:
** Input: `<b><iframe>Test</iframe></b>`
*** Previous behavior: sanitized to `<b>Test</b>`
*** New behavior: sanitized to `<b></b>`
** Input: `<b><i onload="alert('text');" />Test</b>`
*** Previous behavior: sanitized to `<b><i></i>Test</b>`
*** New behavior: sanitized to `<b><i>Test</i></b>`
** Banned tags (such as `<iframe>`) now have their entire content removed, rather than only stripping the tags.
* *Frontend Validation for Date Time Picker* The frontend validation for Date-Time Picker (`@UIDateTimeField`) have changed.
We could not detect any negative impact for linkki applications.
If you experience any unexpected behaviors, please do to hesitate to contact us.

=== Alpha 2.9.0-a20250905-01

==== Bugfixes

// https://jira.convista.com/browse/LIN-4505
* The linkki-bom was published incorrectly and did not contain any `dependencyManagement` entries.
This issue affects only version `2.8.0` and previous alpha version.

=== Alpha 2.9.0-a20250903-01

The release notes contain changes compared to link:https://doc.linkki-framework.org/2.8/00_releasenotes/#_version_2_8_0[version 2.8.0].

==== Version Updates

The following versions have been updated:

[cols="a,a,a"]
|===
| Dependency                    | New version       | Previous version

| Faktor-IPS                    | 25.7.1.release (link:https://doc.faktorzehn.org/faktor-ips/25.7/01_releasenotes/index.html[Release Notes]) | 25.7.0-release
| Vaadin                        | 24.7.12 (link:https://github.com/vaadin/platform/releases/tag/24.7.12[Release Notes]) | 24.7.8
| Spring Boot                   | 3.5.5 (link:https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.5-Release-Notes[Release Notes]) | 3.5.4
| Karibu | 2.4.2 | 2.3.0
| commons-lang | 3.18.0 | 3.17.0
| Junit | 5.13.4 | 5.12.2
|===

==== Other Improvements

* A new section <<tutorial-step-11, UI Tests>> has been added to the <<linkki-tutorial,linkki tutorial>>, demonstrating how to write unit UI tests with Karibu-Testing.

==== Bugfixes
// https://jira.convista.com/browse/LIN-4562
* Testing: The annotation `WithLocale` now works correctly with `@ParameterizedTest`.
// https://jira.convista.com/browse/LIN-3289
* [.api-change]*Grid selection only updates the bindings on changes from client* +
Selection listeners in `GridSelectionAspectDefinition` now check `ComponentEvent#isFromClient` to ensure model updates only occur for user-initiated events.
This reduces the number of unnecessary updates significantly. +
With this fix, setting the selection programmatically using the Vaadin API does not result in an update of all bindings anymore.
While this is the expected behaviors, implementations that previously relied on the binding update may need to be adjusted.
