:jbake-title: Release Notes
:jbake-type: chapter
:jbake-tags: release-notes
:jbake-status: published
:jbake-order: 0
// NO :source-dir: HERE, BECAUSE N&N NEEDS TO SHOW CODE AT ITS TIME OF ORIGIN, NOT LINK TO CURRENT CODE
:images-folder-name: 01_releasenotes

== Release Notes

=== Version 2.8.2

==== Bugfixes

// https://jira.convista.com/browse/LIN-4561
* In version `2.8.1`, entering a value to a cell inside a table created with `@UITableComponent` and traversing with the tab-key results in loosing focus.
Starting with `2.8.2`, the behavior has been fixed.

=== Version 2.8.1

==== Version Updates

The following versions have been updated:

[cols="a,a,a"]
|===
| Dependency | New version | Previous version

| Faktor-IPS                    | 25.7.1.release (link:https://doc.faktorzehn.org/faktor-ips/25.7/01_releasenotes/index.html[Release Notes]) | 25.7.0.release
| Vaadin                        | 24.7.13 (link:https://github.com/vaadin/platform/releases/tag/24.7.13[Release Notes]) | 24.7.8
| Spring Boot compatibility tested for | 3.5.5 (link:https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.5-Release-Notes[Release Notes]) | 3.5.3
|===

==== Bugfixes

// https://jira.convista.com/browse/LIN-4558
* The linkki-bom was published incorrectly and did not contain any `dependencyManagement` entries.
This issue affects only version `2.8.0`.
Starting with `2.8.1`, the BOM has been fixed and works as expected.
// https://jira.convista.com/browse/LIN-4562
* Testing: The annotation `WithLocale` now works correctly with `@ParameterizedTest`.

=== Version 2.8.0

The release notes contain changes compared to link:https://doc.linkki-framework.org/2.7/00_releasenotes/#_version_2_7_1[version 2.7.1].

==== Version Updates

The following versions have been updated:

[cols="a,a,a"]
|===
| Dependency | New version | Previous version

| Java                          | 21        | 17
| Faktor-IPS                    | 25.7.0.release (link:https://doc.faktorzehn.org/faktor-ips/25.7/01_releasenotes/index.html[Release Notes]) | 25.1.2.release
| Vaadin                        | 24.7.8 (link:https://github.com/vaadin/platform/releases/tag/24.7.8[Release Notes]) | 24.5.12
| Spring Boot compatibility tested for | 3.5.3 (link:https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.5-Release-Notes[Release Notes]) | 3.4.3
|===

The Vaadin version update brings some changes that may affect linkki applications:

* The supported Node version is changed from 18 to 20.
* New theme `wrap` on `HorizontalLayout` allowing elements to move to the next line, if there's no space left.
* Testbench: The method `WebElement#getAttribute` is deprecated and should be replaced with `WebElement#getDomAttribute`.

==== Integration of linkki-f10 functionalities into linkki

`linkki-f10` is a library created by Faktor Zehn that provided additional linkki functionalities that are commonly used in Faktor Zehn products, but are not open source.
With this version, classes in `linkki-f10` are fully integrated into linkki, making the code and documentation available at one place.

As part of this transition, all classes in the `linkki-f10` module have been deprecated and replaced by corresponding functionality in the other modules of `linkki`.

In addition to the changes in code, the documentation is now also moved to according sections at link:https://doc.linkki-framework.org[doc.linkki-framework.org].
During this process, the documentation of the affected components has been reworked.

===== Migration

This change requires action from all users of `linkki-f10` or `linkki-f10-search`.
The migration mainly consists of package renamings in imports.

Most notable changes:

* Functionalities previously contained in the `linkki-f10-search` module have been moved to the new <<linkki-search, `linkki-search-vaadin-flow`>> module.
The maven dependency to `linkki-f10-search` must be replaced by dependency to `linkki-search-vaadin-flow`.
The documentation is moved to <<linkki-search, section "Search" in chapter "UI Components">>.
* Maven dependency for `linkki-f10` is no longer available in newer version.
Classes are moved to `linkki-core-vaadin-flow`, `linkki-application-framework-vaadin-flow` or `linkki-vaadin-flow-component` depending on the functionality.
* Most functionalities of `CommonApplicationHeader` are incorporated into <<application-header, `ApplicationHeader`>>.
Functionalities that are related to the user are implemented in the newly introduced <<useraware-application-header,`UserAwareApplicationHeader`>> with the same API.
* `UIMenuList` and `UIMenuButton` now have the default value `DERIVED_BY_LINKKI` for caption.
Therefore, the attribute caption is not mandatory anymore.
Existing declarations that use `DERIVED_BY_LINKKI` can be removed.
* The `NavigationWorkaround` is not needed anymore as the underlying Vaadin bug is fixed.

include::2_8_linkki_f10_migration.adoc[]

==== UI Annotations and Aspects

* *UIHeadline* +
A new UI component, `@UIHeadline`, is now available, providing a way to easily create <<headline, headlines>> that only display text.
// https://jira.faktorzehn.de/browse/LIN-352
* *UIOpenDialogButton* +
Sometimes, a value or a grid item should not be edited directly.
Instead, a dialog should be opened upon a button click in which the user can edit the value in a more complex form.
To implement this use case, `BindingContext#modelChanged` often needs to be passed to the PMO to update the underlying `BindingContext` after the OK button was clicked. +
The new UI annotation <<uiOpenDialogButton, @UIOpenDialogButton>> resolves this inconvenience.
The annotated method returns a `DialogPmo` that is used to create the dialog that is opened upon button click. +
For use with a Faktor-IPS model object, the abstract class <<ips-dialog-pmo, `IpsDialogPmo`>> provides a partial implementation of `DialogPmo`.
When the user clicks on the OK button, the underlying `BindingContext` is updated automatically. +
Alternatively, a `Function` can be returned that defines how to create a dialog that applies the given handler additionally on OK click.
This can be used for use cases where the dialog content cannot be defined as a PMO. +
+
Note that this annotation is an experimental feature that may be subject of API change in the near future.

* *UIMenuList and UIButton* +
New UI components, `@UIMenuList` and `@UIMenuButton`, are now available, providing a way to create <<ui-menulist, buttons in menus>> that can expand a menu list or execute an action, while maintaining a consistent look and feel.

* *BindComboBoxItemStyle* +
<<bind-combo-box-item-style, @BindComboBoxItemStyle>> can now be used together with <<ui-multiselect, `@UIMultiSelect`>>.

* [api-change]*Custom aspects with asynchronously loaded values* +
It is now possible to create custom aspects that load values asynchronously with a `CompletableFuture`.
The documentation for creating custom aspects is extended with a <<aspect-async,how-to guide for creating custom future aware aspects>>. +
+
Additionally, the frontend behaviors of `@UILabel` and `@UITableComponent` considering loading have been unified.
This leads to following breaking changes in the frontend:
+
--
** During loading, the `items-loading` (UITableComponent) / `value-loading` (UILabel) attributes are no longer set.
Instead, the attribute `content-loading` is set.
** The `has-errors` attribute has been renamed to `has-loading-error`.
** The CSS property `error-messages` has been renamed to `loading-error-message`.
** `@UILabel` components in a loading state no longer have the CSS class `loading`.
--

Custom CSS selectors that utilize the above attributes / CSS Properties must be adjusted accordingly.

==== Testing

* *Conditions for AssertJ* +
The utility class <<component-conditions, `ComponentConditions`>> providing UI specific conditions for AssertJ has been added to `linkki-vaadin-flow-test` to support writing more readable assertions such as `assertThat(component).is(childOf(layout))` or `assertThat(component).has(anyChildrenSatisfying(...))`.

* *Component Tree Representation* +
When using AssertJ, the object that is tested is displayed with `toString()` in case of failure.
In case of a `Component`, it is often not immediately clear how the component actually looks like.
The new class <<component-representation, `ComponentTreeRepresentation`>> can be used with `Assertions#withRepresentation` to display the component with the complete component tree in case of failure.

* *Added Functionalities in KaribuUtils* +
** `KaribuUtils#getTextContent` now also returns the text content of layout elements.
** The component tree can now be returned without printing it using `KaribuUtils#getComponentTree`.
** `printComponentTree` and `getComponentTree` also print out all table rows.
** `KaribuUtils.Grids.getTextContentInColumn` also returns the value of an input element such as text field.
The method also supports `TreeGrid` now, but only displays root items.
** Added `KaribuUtils.ComboBoxes#setValueByLabel` to set the value within a combobox based on a label.
** Added `KaribuUtils.Dialogs#getFirstMessage` to get the component of the first validation message in a OkCancelDialog.

* [api-change]*Method renaming within KaribuUtils.ComboBoxes* +
Methods in `KaribuUtils.ComboBoxes` are renamed to make them more consistent to methods in `Fields`:
** `getComboBoxWithId` -> `getWithId`
** `setComboBoxValue` -> `setValue`

==== Other Improvements

* *New documentation chapter - How-To* +
Introduced a <<linkki-howto, How-To>> chapter containing coding examples and best practises.

* [api-change]*Relocation of UINestedComponent* +
`UINestedComponent` has been moved from `linkki-core-nestedcomponent-vaadin-flow` to `linkki-core-vaadin-flow`.
The module `linkki-core-nestedcomponent-vaadin-flow` has been removed.

* *New theme variant for form item label alignment* +
The new <<linkki-theme-variants,theme variant>> `form-item-label-start` can be used to create sections with left aligned labels on form items.
The variant can be applied to a single layout using `@BindVariantNames`.

* *New Utility CSS class for nested flex items* +
The class `flex-basis-0` sets the initial size of flex items to zero, allowing flex items to grow based only on the available space.
It is also available as the constant `LinkkiTheme.Flex.BASIS_NONE`.

==== Bugfixes
// https://jira.faktorzehn.de/browse/LIN-4248
* `SimpleItemSupplier` now throws a `NullPointerException` if the model object to PMO mapping supplier returns `null`.
// https://jira.convista.com/browse/LIN-4262
* `linkki-vaadin-flow-test` no longer includes `vaadin-dev`, and `linkki-vaadin-flow-testbench-extension` now marks `vaadin-core` as provided.
This avoids unwanted dependencies in production.