:jbake-title: Create a UI from the Presentation Model Object
:jbake-type: section
:jbake-status: published
:source-dir: ../../../../../../vaadin14/samples/test-playground/src/main/java

[[pmo-create-ui]]
=== Create a UI from the Presentation Model Object (PMO)

A UI is built using different component containers, in HTML typically represented by a `<div>`. In *linkki* as in Vaadin we call these component containers _layouts_. Every layout is represented by a PMO, short for _presentation model object_. A PMO is primarily a simple POJO that is annotated with special *linkki* annotations. For every component in the layout, a bean property (represented by a getter and setter method) is defined within this PMO.

When a class is annotated with a <<layout,layout annotation>> like `@UISection`, *linkki* takes control over the creation and arrangement of the defined components. Using annotations for the <<ui-element, UI elements>>, certain aspects can be defined or controlled. The layouts are created using the `VaadinUiCreator`.

The <<ui-element, `UI elements`>> are bound either to the 'properties' of a `ModelObject` or a PMO. A detailed description can be found in the chapter <<domain-model-binding, `Data on Multiple Layers`>>.

TIP: In all cases, if the `ModelObject` or PMO doesn't have a corresponding setter, the field is `readOnly`.

The following examples describe how to create a standard forms section, followed by an example of how to create a table section. There are some more available <<layout, layout annotations>> and it is quite easy to write a <<custom-ui-layout-annotation,custom layout annotation>>.

[[form-binding]]
==== Creating a Form Section

[[binding-model-object]]
.Binding with `@ModelObject`

[source,java]
----
include::{source-dir}/org/linkki/samples/playground/binding/pmo/ContactSectionPmo.java[tags=contactPmo-class]
----

TIP: The definition of `modelAttribute` is optional if the property name in the `ModelObject` and the name of the annotated method are equal. But it
is recommended to specify the `modelAttribute` to make it explicit. The value should be externalized to a constant in the target model object as seen for the `lastname` property.

[[binding-table]]
==== Creating a Table Section

To create a section with a table the PMO class must implement <<ui-container-pmo, `org.linkki.core.defaults.columnbased.pmo.ContainerPmo<ROW>`>>. The generic parameter `ROW` represents the type of the PMO to create a row in this table.

[source,java]
----
include::{source-dir}/org/linkki/samples/playground/binding/pmo/ContactTablePmo.java[tags=contactTablePmo-class]
----

The method `getItems()` returns the rows of the table in the form of the previously defined `ROW` 'row PMOs'.

[source,java]
----
include::{source-dir}/org/linkki/samples/playground/binding/pmo/ContactTablePmo.java[tags=contactTablePmo-getItems]
----

In the `interface ContainerPmo<ROW>` additional `default` methods are defined. A detailed description can be found in the section about <<ui-container-pmo, ContainerPmo>>.

The so called 'Row PMO' is a regular PMO as described in <<form-binding, the first section>>. The only difference is that the UI elements may optionally be annotated with <<ui-table-column, `@UITableColumn`>>.

[source,java]
----
include::{source-dir}/org/linkki/samples/playground/binding/pmo/ContactRowPmo.java[tags=contactRowPmo-labelBinding]
----

All UI elements can be used in tables. The binding of a `@UIButton` looks as follows:

[source,java]
----
include::{source-dir}/org/linkki/samples/playground/binding/pmo/ContactRowPmo.java[tags=contactRowPmo-buttonBinding]
----

NOTE: In our example the elements of the table shall be presented as read-only. Therefore no direct binding of the `ModelObject` via the `@ModelObject` annotation is done. If the items of your table are provided from a model object you may consider to use `org.linkki.core.defaults.columnbased.pmo.SimpleTablePmo<MO, ROW>` which is described in chapter <<ui-tables, Tables>> in detail.
