:jbake-title: Components
:jbake-type: section
:jbake-status: published

[[f10-components]]
=== Components

[[board-layout]]
==== BoardLayout

`BoardLayout` arranges multiple `BoardComponents` as cards. The `BoardComponents` are ordered row-wise.

Every element on the board is represented by an instance of the class `BoardComponent`. Each `BoardComponent` comprises a title and a `Component`.
This component can be assigned via the `BoardComponent` constructor so that no further inheritance is needed.

[TIP]
The component can either be a Vaadin `Component` or a PMO.

Additionally, `BoardComponent` provides two theme variants: `MEDIUM` and `LARGE`. A `BoardComponent` with variant `LARGE` has double the width compared to `MEDIUM`.

.How To: Using BoardLayout as a View
====
.Example Implementation of BoardLayout
[source, java]
----
@Route(value = "", layout = MyApplicationLayout.class) // 2
public class MyBoardLayout extends BoardLayout { // 1

  public MyBoardLayout() {
    super(new BoardComponent("name", new MyBoardPmo()), // 3
          new BoardComponent("another name", new MyBoardComponent(), BoardComponentVariant.LARGE));
  }
}
----

`BoardLayout` is often used as the home page of the application, which can be implemented as follows:

* Create a subclass of `BoardLayout`
* Annotate the subclass with `@Route` and configure the route (value) and the used layout class (layout)
* Create `BoardComponent` instances within the constructor

====

[[ui-menulist]]
==== @UIMenuList and @UIMenuButton

Within menus, `@UIMenuList` can be used to create a button that shows a list of menu items when clicked.
`@UIMenuButton` can be used to create buttons that look and feel consistent with respect to `@UIMenuList` buttons.
These, however, show no menu items but rather directly execute an action when clicked.

[[menu-item-definition]]
===== Usage of @UIMenuList

A method annotated with `@UIMenuList` must return a list of `MenuItemDefinition`. These form the list of menu items that will be shown when the button is clicked.

.Implementation of a method annotated with @UIMenuList
[source, java]
----
@UIMenuList(position = 0, caption = "Menu", icon = VaadinIcon.LIST)
public List<MenuItemDefinition> getMenu() {
    return List.of(
        MenuItemDefinition.builder("id1")
                          .caption("First Menu Item")
                          .command(() -> firstFunction())
                          .visibleIf(isFirstMenuItemVisible())
                          .build(),
        MenuItemDefinition.builder("id2")
                          .caption("Second Menu Item")
                          .command(() -> secondFunction())
                          .enabledIf(isSecondMenuItemEnabled())
                          .build());
}
----

`MenuItemDefinition` instances are created using a builder that can be created using the static method `builder`. Each `MenuItemDefinition` must have an ID. Hence, it is required for creating the builder.


[NOTE]
The final ID of a menu item is a combination of the menu button ID and the menu item ID. Regarding the above example, there would be a menu item with ID `menu`. This name would be derived from the methods name or the PMO property name. The menu item IDs in the example would have the IDs `menu-id1` and `menu-id2`, respectively.

[WARNING]
IDs within a menu must be unique. If this is violated and multiple items share the same ID, an exception will be thrown.

A menu item should show a caption and define a command that is executed when the item is clicked. Optionally, a menu item can be assigned an icon.

[IMPORTANT]
Usage of icons should follow the https://doc.faktorzehn.de/produkt-ui-guide/07_uikomponenten/08_icons.html[UI Guide].

Additionally, a button can be disabled or made invisible calling either `#enabledIf` or `#visibleIf` on the `MenuItemDefinition` builder. This property will update dynamically by using the items ID.

[WARNING]
The method annotated with `@UIMenuList` is called with *every* UI update. +
It is, therefore, important to avoid computationally expensive operations. +
Although, the method is called with every update, only the visibility and enabled state are updated but *no other aspects* such as the caption or the list of menu items. However, a dynamic list can be implemented using the visibility and enabled state.