:jbake-title: Components
:jbake-type: section
:jbake-status: published

[[f10-components]]
=== Components

[[board-layout]]
==== BoardLayout

`BoardLayout` arranges multiple `BoardComponents` as cards. The `BoardComponents` are ordered row-wise.

Every element on the board is represented by an instance of the class `BoardComponent`. Each `BoardComponent` comprises a title and a `Component`.
This component can be assigned via the `BoardComponent` constructor so that no further inheritance is needed.

[TIP]
The component can either be a Vaadin `Component` or a PMO.

Additionally, `BoardComponent` provides two theme variants: `MEDIUM` and `LARGE`. A `BoardComponent` with variant `LARGE` has double the width compared to `MEDIUM`.

.How To: Using BoardLayout as a View
====
.Example Implementation of BoardLayout
[source, java]
----
@Route(value = "", layout = MyApplicationLayout.class) // 2
public class MyBoardLayout extends BoardLayout { // 1

  public MyBoardLayout() {
    super(new BoardComponent("name", new MyBoardPmo()), // 3
          new BoardComponent("another name", new MyBoardComponent(), BoardComponentVariant.LARGE));
  }
}
----

`BoardLayout` is often used as the home page of the application, which can be implemented as follows:

* Create a subclass of `BoardLayout`
* Annotate the subclass with `@Route` and configure the route (value) and the used layout class (layout)
* Create `BoardComponent` instances within the constructor

====