:jbake-title: F10 Theme
:jbake-type: section
:jbake-status: published

[[f10-styles]]
=== F10 Vaadin Flow Styling

The *linkki-f10* module provides its own theme and sets its own primary color.

==== Integrating F10 Themes

A description on how to integrate the *linkki* theme can be found in the "Styling" chapter of the *linkki* documentation. The *F10 theme* can be integrated analogously and its name is provided within the constant `F10ProductTheme.F10_PRODUCT_THEME`.

[[primary-color]]
==== Setting a Primary Color

By default, a dark blue (hsl(206,100%,30%) / rgb(0,87,153) / #005799) is used a primary color. This color is intended to be used in sample applications. In customer projects, however, it is often customized.

To do so, a new theme must be created within the application project extending the *F10 theme*. A guide can be found within the "Styling" chapter of the *linkki* documentation under "Customizing the linkki theme".

[NOTE]
Use `"f10-product"` instead of `"linkki"` as parent within the `theme.json`.

The primary color can then be customized within the `styles.css`. It is set via the following three css properties:

* `--f10-primary-color-h`
* `--f10-primary-color-s`
* `--f10-primary-color-l`


Using the above properties, further color gradings (such as the primary text color `--lumo-primary-text-color`) are derived and calculated. Other values are usually derived too and do not need to be customized.

In total, the following constants are available:

* `--f10-primary-color-h`: Primary color value (default: 206)
* `--f10-primary-color-s`: Primary color saturation (default: 100%)
* `--f10-primary-color-l`: Primary color relative brightness (default: 30%)
* `--f10-primary-color`: Primary color. By default, calculated from `--f10-primary-color-h`, `--f10-primary-color-s` and `f10-primary-color-l`.
* `--f10-primary-contrast-color`: Primary color contrast. For example, used for text within the application header and derived by default.