:jbake-title: Search
:jbake-type: section
:jbake-status: published
:source-dir: ../../../../../samples/linkki-f10-sample

[[linkki-f10-search]]
=== Search

The *linkki* provides search components that can be used by any product for performing primary search operations.

The search can be integrated in two ways:

* As a separate site (also referred to as link:https://doc.faktorzehn.de/produkt-ui-guide/07_uikomponenten/05_suche.html#_kontextfreie_suche[context-free])
* Within another site (also referred to as link:https://doc.faktorzehn.de/produkt-ui-guide/07_uikomponenten/05_suche.html#_kontextabh%C3%A4ngige_suche[context-dependent])

==== Necessary Classes

Independent of the kind of search, there are several classes that need to be created.

[horizontal]
Search Parameter :: Model object for search parameters.
+
.`SampleSearchParameters`
[source, java]
----
public class SampleSearchParameters {

    public static final String PROPERTY_PARTNER_NUMBER = "partnerNumber";
    // and other search parameters

    private String partnerNumber;

    public String getPartnerNumber() {
        return partnerNumber;
    }

    public void setPartnerNumber(String partnerNumber) {
        this.partnerNumber = partnerNumber;
    }

}
----

PMO for Search Parameter:: A PMO for the search parameter object to implement the input of search parameters in the UI.
+
.`SampleSearchParametersPmo`
[source,java]
----
include::{source-dir}/src/main/java/org/linkki/samples/f10/search/SampleSearchParametersPmo.java[tags=sampleSearchParametersPmo]
----
+
The first UI element annotated with `@BindAutoFocus` makes the element being automatically selected with a focus ring within the browser.

Collected Search Results :: Wrapper for a list of singular search results. Note that it must be possible to read out a `MessageList` containing possibly occurred errors from the list of search results. Hence, it is recommended to save the messages of the search service here, too.
+
.`SampleSearchResult`
[source,java]
----
include::{source-dir}/src/main/java/org/linkki/samples/f10/search/service/SampleSearchResult.java[tags=SampleSearchResult]
----

Single Search Result:: Model object of a single search result
+
.`SampleModelObject`
[source,java]
----
public class SampleModelObject {

    private final String partnerNumber;
    // and other properties

    public SampleModelObject(String partnerNumber) {
        this.partnerNumber = partnerNumber;
    }

    public String getPartnerNumber() {
        return partnerNumber;
    }
}
----

PMO for a single Search Result:: PMO for visualizing the search result as a row in the result table.
+
.`SampleSearchResultRowPmo`
[source, java]
----
public class SampleSearchResultRowPmo {

    private SampleModelObject modelObject;
    private List<MenuItemDefinition> additionalActions;

    public SampleSearchResultRowPmo(SampleModelObject result,
            List<MenuItemDefinition> additionalActions) {
        this.modelObject = result;
        this.additionalActions = additionalActions;
    }

    public SampleModelObject getModelObject() {
        return modelObject;
    }

    @UILink(position = 10, label = "PartnerNumber")
    public String getPartnerNumber() {
        return modelObject.getLink();
    }

    public String getPartnerNumberCaption() {
        return modelObject.getPartnerNummber();
    }

    @UISearchResultAction
    public List<MenuItemDefinition> getActions() {
        return additionalActions;
    }
}
----
+
The RowPMO can be annotated with `@UISearchResultAction` to define actions for a table row. These actions are available at the end of a row in a menu.

===== SearchController

The `SearchController` is responsible for the execution of the actual search. Based on the search type (context-free or context-dependent), its implementation and usage differs. Details can be found within the chapters regarding <<context-free-search, context-free search>> and <<context-dependent-search, context-dependent search>>.

[[search-layout-pmo]]
===== Creating the Search Component

The search component needs a `SearchLayoutPmo` that is created using the `SearchLayoutBuilder` class.

.Example implementation of a search component using `SearchLayoutBuilder<PARAM, RESULT, MODELOBJECT, ROW>`
[source,java]
----
include::{source-dir}/src/main/java/org/linkki/samples/f10/search/contextdependent/ContextDependentSearchView.java[tags=searchLayoutBuilder]
----

The "primary action" is executed upon double-clicking the search result row. When using a context-free search, it is common to open the entry in a new site. The common action for a context-dependent search is to select the entry.

[[context-free-search]]
==== Search as a separate Site

While searching on a separate site, it is desirable to have search parameters that are reflected within the URL. Thereby, a search would also be reachable from another site.

The class `RoutingSearchController` provides functionalities to achieve this.

===== SearchView

Since the search site must be reachable per URL, a `@Route` annotation is needed. Besides that, both the `BeforeEnterObserver` or `AfterNavigationObserver` interface must be implemented to enable URL parameter processing.

[source,java]
----
include::{source-dir}/src/main/java/org/linkki/samples/f10/search/contextfree/ContextFreeSearchView.java[tags=ContextFreeSearchView]
----

[NOTE]
The https://vaadin.com/docs/latest/flow/routing/lifecycle[Vaadin Navigation Lifecycle] documentation proposes the usage of the `AfterNavigationEvent` to initialise the UI. However, this event prevents from redirecting to other sites. In cases where the search result should directly be opened, using the `BeforeEnterEvent` is preferable.

The content of the site must be a `SearchLayoutPmo` that is created using `SearchLayoutBuilder`. Creating a `SearchLayoutPmo` is independent of the actual search and is described in detail in "<<search-layout-pmo, Erstellen der Suchkomponente>>".

[source,java]
----
include::{source-dir}/src/main/java/org/linkki/samples/f10/search/contextfree/ContextFreeSearchView.java[tags=content]
----

The search controller must be initialised and needs the value of the `@Route` annotation as first parameter.
[source, java]
----
include::{source-dir}/src/main/java/org/linkki/samples/f10/search/contextfree/ContextFreeSearchView.java[tags=searchController]
----

Finally, within `afterNavigation` the `AfterNavigationEvents` `Location` must be used to `initialize` the `RoutingSearchController`. The search controller then reads the search parameters of the URL and executes the search if necessary.

[NOTE]
The search parameters can be visualised by updating the `BindingContext` containing the `SearchlayoutPmo`.

[source, java]
----
include::{source-dir}/src/main/java/org/linkki/samples/f10/search/contextfree/ContextFreeSearchView.java[tags=initialize]
----

===== Query Parameter Mapping

An implementation of `SearchParameterMapper` must be created for the search parameter type.

[source,java]
----
include::{source-dir}/src/main/java/org/linkki/samples/f10/search/service/SampleSearchParametersMapper.java[tags=SampleSearchParametersMapper]
----

The `toSearchParameters` method creates a search parameter object based on the query parameters:

[source,java]
----
include::{source-dir}/src/main/java/org/linkki/samples/f10/search/service/SampleSearchParametersMapper.java[tags=toSearchParameters]
        ...
----

Consequently, `toQueryParameters` creates query parameters from a given search parameter object:

[source,java]
----
include::{source-dir}/src/main/java/org/linkki/samples/f10/search/service/SampleSearchParametersMapper.java[tags=toQueryParameters]
        ...
----

In case that every parameter only has one value, `ParamsUtil.flatten` can be used to use `Map<String, String>` instead of `Map<String, List<String>>`. Besides that, `ParamsUtil` offers some handy `format` and `parse` methods.

[source,java]
----
include::{source-dir}/src/main/java/org/linkki/samples/f10/search/service/SampleSearchParametersMapper.java[tags=formatIsoDate]

include::{source-dir}/src/main/java/org/linkki/samples/f10/search/service/SampleSearchParametersMapper.java[tags=parseIsoDate]
----

[[context-dependent-search]]
==== Search within one site

The class `SimpleSearchController` can be used in cases where a search on the current site is needed, e.g., within a dialog.

A `SearchLayoutPmo` is again needed but independent of the kind of search and its creation is described in the chapter "<<search-layout-pmo, Creating a Search Component>>".

===== Example

.Dialog
[source,java]
----
include::{source-dir}/src/main/java/org/linkki/samples/f10/search/contextdependent/ContextDependentSearchView.java[tags=showSearchDialog]
----

.SimpleSearchController
[source,java]
----
include::{source-dir}/src/main/java/org/linkki/samples/f10/search/contextdependent/ContextDependentSearchView.java[tags=SimpleSearchController]
----