:jbake-title: Creating a new aspect
:jbake-type: section
:jbake-status: published

:source-dir: ../../../java

[[creating-aspects]]
=== Creating a new aspect

In addition to built-in aspects, you can easily create your own. This guide walks you through the process of implementing a simple aspect that allows components to show a dynamically bound tooltip. In this example, you will build the aspect as a standalone annotation that can be used in addition to any `BindingDefinition`.

TIP: This aspect is already included in linkki. It is only used as an example due to its simplicity.

==== Create a new aspect annotation

We first create a new annotation that later links the annotated component to an aspect definition:

```java
include::{source-dir}/org/linkki/doc/BindTooltip.java[tags=BindTooltip]
```

* The annotation must have the retention policy `RetentionPolicy#RUNTIME` to be able to be discovered by linkki at runtime.
* The attribute `tooltipType` determines whether the tooltip is static text or is provided by a method dynamically.
* If the `tooltipType` is `BindTooltipType#STATIC`, the attribute `value` allows the user to define the content of the tooltip.

TIP: Using the name `value` for an annotation's attribute allows users to omit the attribute name if it is the only attribute: `@BindTooltip("My tooltip")` instead of `@BindTooltip(value="My tooltip")`

==== AspectDefinition

An aspect definition defines how an aspect is created. To define your own definition you have to implement `LinkkiAspectDefinition` with the following three methods:

* `initialize(Annotation)`: Initializes the aspect by providing the annotation that is annotated with `@LinkkiAspect`.
* `initModelUpdate(PropertyDispatcher, ComponentWrapper, Handler)`: Method that registers a listener to the wrapped UI component which react to changes in the UI. This method is only mandatory if the defined aspect needs to write into the model.
* `createUiUpdater(PropertyDispatcher, ComponentWrapper)`: Creates a `Handler` that is triggered when the UI has to be updated.

An aspect definition that uses the newly defined annotation `@BindTooltip` would look as follows:

```java
include::{source-dir}/org/linkki/doc/BindTooltipAspectDefinition.java[tags=BindTooltipAspectDefinition]
```

* `initModelUpdate` is not needed in this example because the tooltip won't change in the model upon UI change.
* In the method `createUiUpdater`,  the `propertyDispatcher` is asked for the tooltip value which is then set in the component using `ComponentWrapper#setTooltip`. The `propertyDispatcher` needs an aspect to know which value it should retrieve, and how. This aspect is created in the method `createAspect()`.
* `createAspect()` creates the aspect depending on the values given in the annotation.
* The `BindTooltip`-annotation is stored by the `initialize(Annotation)` method to be used in `createAspect()`.

==== @LinkkiAspect Annotation

Lastly, `BindTooltip` has to be annotated with `@LinkkiAspect(BindTooltipAspectDefinition.class)` to bring the `BindTooltip` annotation and `BindTooltipAspectDefinition` together.

```java
include::{source-dir}/org/linkki/doc/BindTooltip.java[tags=BindTooltipLinkkiAspect]
```

==== Summary
Congratulations! You have implemented a new tooltip aspect that can be used with any other linkki UI annotation. With this aspect, you can add a static or dynamic tooltip to a UI element that is bound by linkki.
