:jbake-title: Getting Started
:jbake-type: chapter
:jbake-status: published
:jbake-order: 1

:sample-parent-dir: ../../../../../../vaadin14/samples

[[getting-started]]
== Getting Started

You can either add the required dependencies to an existing project or use one of the <<maven-archetypes,Maven archetypes>> to get started.

=== Maven dependencies

To create a *linkki* project with Vaadin 14, you need one of the following dependencies depending on the feature set you need:

.linkki-core
[source,xml]
----
include::{sample-parent-dir}/pom.xml[tags=linkki-core]
----

.linkki-vaadin14-component
[source,xml]
----
include::{sample-parent-dir}/pom.xml[tags=linkki-vaadin14-component]
----

`linkki-vaadin14-component` contains the following additional features:

* Sidebar layout

.linkki-application-framework
[source,xml]
----
include::{sample-parent-dir}/pom.xml[tags=linkki-application-framework]
----

`linkki-application-framework` contains the following additional features:

* Dialogs
* `LinkkiUi` with `ApplicationLayout` and `ApplicationConfig` as well as an adjusted theme
* UI Components to display validation messages


In addition to the *linkki* dependency, a *linkki* application with Vaadin may require a Vaadin Spring Boot starter.


[[maven-archetypes]]
=== Maven Archetypes

*linkki* can be used for a plain Vaadin web application, with Spring Boot or with CDI. For each of those options, there is a matching Maven archetype that creates a new project with all necessary dependencies and some sample code to get started. They can be created from a command line:

[source,subs="verbatim,attributes"]
.Plain *linkki*
----
mvn archetype:generate -DarchetypeGroupId=org.linkki-framework.archetypes -DarchetypeArtifactId=linkki-archetype-plain-application-vaadin14 -DarchetypeVersion={projectVersion}
----

The resulting application can be deployed to your application server of choice or simply started with `mvn clean package org.eclipse.jetty:jetty-maven-plugin:run`, where it can be viewed at `http://localhost:8080/main`.

[source,subs="verbatim,attributes"]
.*linkki* with CDI
----
mvn archetype:generate -DarchetypeGroupId=org.linkki-framework.archetypes -DarchetypeArtifactId=linkki-archetype-cdi-application-vaadin14 -DarchetypeVersion={projectVersion}
----

The resulting application can be deployed to your Java Enterprise Edition 7+ server of choice or simply started with `mvn clean package org.apache.tomee.maven:tomee-maven-plugin:run`, where it can be viewed at `http://localhost:8080/[yourArtifactId]`.

[source,subs="verbatim,attributes"]
.*linkki* with Spring Boot
----
mvn archetype:generate -DarchetypeGroupId=org.linkki-framework.archetypes -DarchetypeArtifactId=linkki-archetype-spring-application-vaadin14 -DarchetypeVersion={projectVersion}
----

The resulting application can be started with `java -jar target/*.war` and be viewed at `http://localhost:8080/`.
