:jbake-title: Vaadin 14 Migration
:jbake-type: chapter
:jbake-status: draft
:jbake-order: 1000


== Vaadin 14 Migration

=== Application Framework

==== Messages
* Deprecated `Message*` classes have been removed
** `MessageListPanel` has been replaced by `MessageUiComponents#createMessageTable`
** `MessagePmo` has been replaced by `MessageRowPmo`
** `MessageRow` has been replaced by `MessageUiComponents#createMessageComponent`

==== LinkkiUi
////
https://jira.faktorzehn.de/browse/LIN-2042
////
`LinkkiUi` has been removed

* Create new class `MyApplicationLayout`, extending `ApplicationLayout` and override `ApplicationLayout#getApplicationConfig` to return your `ApplicationConfig`. `ApplicationLayout` itself is implementing `RouterLayout` to be used as a navigation target `Component`.
* Create new class `MySampleView`, which should be used as an entry point for navigable view annotated with `@Route(value = MySampleView.NAME, layout = MyApplicationLayout.class)` and add further View-`Components` .

In addition following changes have been made:

* Navigation has been replaced by Routing, using the `@Route` annotation at the corresponding `Component` itself
** `ApplicationNavigator` has been removed
** `ApplicationLayout#createApplicationNavigator` has been removed

* `ApplicationConfig#createApplicationLayout` has been removed 
** Replaced by extending `ApplicationLayout`

* `ApplicationHeader` and `ApplicationFooter` are now extending `Composite<HorizontalLayout>` instead of `HorizontalLayout` directly
* `MessageUiComponents` are now displayed using `Grid` instead of `Table`
* linkki dialogs  are now extending `Composite<Dialog>` instead of `Window`. See `OkCancelDialog`.

=== Components

==== TabSheetArea has been replaced by LinkkiTabLayout
////
https://jira.faktorzehn.de/browse/LIN-2158
////

* `TabSheetArea#addTab` -> `LinkkiTabLayout#addTabSheet`
* `TabSheetArea#createContent` to add tabs using `TabSheetArea#addTab` has been removed. Instead, `LinkkiTabLayout#addTabSheet` should be used
* `TabSheetArea#updateContent` has been removed.

===== SidebarLayout has been replaced by LinkkiTabLayout

[source,java]
----
-- Vaadin 8
SidebarLayout sidebarLayout = new SidebarLayout();
-- Vaadin 14
LinkkiTabLayout linkkiTabLayout = LinkkiTabLayout.newSidebarLayout();
----

* `SidebarLayout#addSheet` -> `LinkkiTabLayout#addTabSheet`
* `SidebarLayout#addSheets` -> `LinkkiTabLayout#addTabSheets`
* `SidebarLayout#addSelectionListener` -> `LinkkiTabLayout#addSelectedChangeListener`
* `SidebarLayout#select(id)` -> `LinkkiTabLayout#setSelectedTabSheet(sheet.getId())`
* `SidebarLayout#select(sheet)` -> `LinkkiTabLayout#setSelectedTabSheet(sheet.getId())`
* `SidebarLayout#getSelected` -> `LinkkiTabLayout#getSelectedTabSheet`
* `SidebarLayout#getSidebarSheet(id)` -> `LinkkiTabLayout#getTabSheet(id)`
* `SidebarLayout#getSidebarSheets` -> `LinkkiTabLayout# getTabSheets`
* `SidebarSelectionEvent#getOldValue` -> `SelectedChangeEvent#getPreviousTab`
* `SidebarSelectionEvent#getSelectedSheet` -> `SelectedChangeEvent#getSelectedTab`

===== SidebarSheet has been replaced by LinkkiTabSheet

[source,java]
----
-- Vaadin 8
SidebarSheet sidebarSheet = SidebarSheet(id, icon, name, contentSupplier, uiUpdateObserver);
-- Vaadin 14
LinkkiTabSheet linkkiTabSheet = LinkkiTabSheet.builder(id)
				.caption(icon.create()) //.caption(String)
				.description(name)
				.content(contentSupplier) // .content(Component)
				.onSelectHandler(uiUpdateObserver)
				.build();
----

* `SidebarSheet#getButton().getIcon()` -> `LinkkiTabSheet#getTab().getChildren().findFirst().get()`
* `SidebarSheet#getName` -> `LinkkiTabSheet#getDescription`

==== @UIButton
////
https://jira.faktorzehn.de/browse/LIN-2142
////
* `styleNames()` has been replaced by `variants()`, which now returns an Array of `ButtonVariant`
* `shortcutKeyCode` now returns `String[]`. Commonly used `KeyCodes` in linkki are defined in `KeyCode`. An overview of all supported keys can be found in Vaadin's `Key` class. 
* `shortcutModifierKeys` now returns an Array of `KeyModifier`. For a list of available modifiers, see Vaadin's enum class `KeyModifier`.

==== @UIDateField
////
https://jira.faktorzehn.de/browse/LIN-2044
https://jira.faktorzehn.de/browse/LIN-2091
////
The date format of a @UIDateField is now controlled by `DateFormats` and the locale, the attribute `dateFormat` has been removed.

==== @UITextArea
////
https://jira.faktorzehn.de/browse/LIN-2059
////
Attribute `rows` does not exists anymore. It has been replaced by `height`, which returns a `String`, specifying the height of the component using a number and a CSS unit, for example "5em".

==== @UILabel
////
https://jira.faktorzehn.de/browse/LIN-2053
////
The usage of the `ContentMode` for `@UILabel` in Vaadin 8 has changed. Instead of setting `Label#setContentMode` to `true` when using `Label#htmlContent` , you can use `getElement().setProperty("innerHTML", "<b>My html content</b>")` of the corresponding component, as now used in linkki `LabelValueAspectDefinition`.

For a further example, see https://vaadin.com/forum/thread/17133860/label-contentmode-html

==== ComponentFactory
////
https://jira.faktorzehn.de/browse/LIN-2053
////
Following `*Label` methods have been removed, as `Label` has been replaced by `LinkkiText`:

* `newLabelWidth100(parent, caption)`
* `sizedLabel(parent, caption, contentMode)`
* `sizedLabel(parent, caption)`
* `newLabelWidthUndefined(parent, caption)`
* `labelIcon(parent, fontIcon)`
* `newEmptyLabel(layout)`
* `newLabelIcon(fontIcon)`
* `newLabelFullWidth(caption, contentMode)`
* `newLabelFullWidth(caption)`
* `newLabelUndefinedWidth(caption, contentMode)`
* `newLabelUndefinedWidth(caption)`

==== Component#setIcon
The `setIcon` method for `Component` has been deleted. It is only available for `@UIButton` and components, that are implementing the `HasIcon` interface, like the ones created by `@UILabel` and `@UILink`.

==== Resource / Icon
`com.vaadin.server.Resource` for icons in Vaadin 8 has been replaced by `VaadinIcon#create`

==== Tables have been replaced by Grids
////
https://jira.faktorzehn.de/browse/LIN-2088
////
In Vaadin 14, `Table` has been replaced by `Grid`

* `PmoBasedTablefactory` has been replaced by `GridComponentCreator`
* `@UITableColumn`: `expandRatio` replaced by `flexGrow`. The `flexGrow` specifies what amount of the available space inside the table the column should take up and grow (if resized), proportionally to the other columns. If `flexGrow` is set to 0, the column has a fixed `width`.

=== Aspect annotations

==== @BindIcon
The `@BindIcon` annotation is available for `@UIButton` and all components, that are implementing the `HasIcon` interface. At the moment, these are `@UILabel` and `@UILink`. Using `htmlContent` of the `@UILabel` will override any icon.

=== NLS

==== TextProvider
////
https://jira.faktorzehn.de/browse/LIN-2123
////
It is recommended to provide an implementation of `I18NProvider` as following, to ensure `UI#getLocale` returns the best matching `Locale` corresponding to the user agent's preferences (i.e. the `Accept-Language` header). If no `I18NProvider` is available, the default JVM `Locale` is used.

[source,java]
----
@Component
public class MyI18NProvider implements I18NProvider {
	...
}
----

=== Styling
////
https://jira.faktorzehn.de/browse/LIN-2249
////
==== Theming
Valo theme has been replaced by Lumo theme. For more information see https://vaadin.com/docs/flow/migration/6-theming.html

==== Tooltips
////
https://jira.faktorzehn.de/browse/LIN-2054
////
By now, tooltips are only supported by `LinkkiTabSheet`, using the `LinkkiTabSheet#description` property. Other UI components currently do not support tooltips. For more information see https://vaadin.com/forum/thread/17094165/tooltips