:jbake-title: Vaadin 14 Migration
:jbake-type: chapter
:jbake-status: published
:jbake-order: 1000

== Vaadin 14 Migration

Stichpunkte, die in der Migrationsanleitung geordnet und ausformuliert werden

* Tooltips gibts nicht mehr? https://vaadin.com/forum/thread/17094165/tooltips
* Valo theme gibts nicht mehr: https://vaadin.com/docs/flow/migration/6-theming.html
* Content mode gibts nicht mehr? https://vaadin.com/forum/thread/17133860/label-contentmode-html
* Resource -> Icon
* Component#setIcon gibts nicht mehr
* @BindIcon
    ** für Buttons und alle Komponenten die HasIcon implementieren (LinkkiText und LinkkiAnchor)
    ** Funktioniert nicht in Kombination mit htmlContent am Label. Der htmlContent 'überschreibt' das Icon
* Man muss einen I18NProvider setzen, sonst wird die default system locale genommen -> LIN-2123
* ComponentFactory: Label methoden gelöscht -> Umstellung + LIN-2053
* UIDateField unterstützt kein custom Date-Format mehr. Das Format ist durch das zugrundeliegende Locale festgelegt (Vaadin benutzt angeblich das hier zum mapping). Das Attribut 'dateFormat' ist dementsprechend rausgeflogen, muss auch in UIDateField dokumentation angepasst werden -> LIN-2044, LIN-2091
* TextArea hat kein `rows` Attribute mehr. In `UITextArea` wurde der Parameter `rows` deshalb durch `height` ersetzt. Dieser gibt einen String an, der einen CSS-Wert darstellt. (LIN-2059)
* @UITableColumn#expandRatio heiß jetzt flexGrow
** Nimmt jetzt Integer statt Float
** Funktion siehe Vaadin Doku
* GridComponentCreator statt PmoBasedTablefactory verwenden. Die Factory wurde auf deprecated gesetzt.
* @UIButton 
** styleNames() entfernt -> ersetzt durch variants() (LIN-2142)
** shortcutKeyCode und shortcutModifierKeys geben nun String Arrays zurück statt int Arrays. Werte, die verwendet werden können, können in der Klasee `Key` von Vaadin nachgeschaut werden. Die Klasse `KeyCode` von linkki enthält gängige Werte und wird bei Anforderungen ergänzt. Für Modifier wird von Vaadin eine Enum Klasse `KeyModifier` angeboten. 

=== Application Framework

* LinkkiUi wurde entfernt
* Ableitung von ApplicationLayout als Einsprungspunkt für die Anwendung. ApplicationLayout muss/ kann als RouterLayout für Komponenten verwendet werden zu denen navigiert werden kann
** ApplicationConfig#createApplicationLayout wurde entfernt
* Der ApplicationNavigator wurde entfernt
** Navigator durch Routing ersetzt. Annotationen direkt an den Komponenten
** ApplicationLayout#createApplicationNavigator wurden entfernt
* ApplicationHeader und ApplicationFooter wurden auf Composite umgestellt
* Deprecated Message Komponenten wurden entfernt
* MessageUiComponents auf Grid umgestellt
* Label durch Text ersetzt
* Dialoge von Window auf Dialog umgestellt

* SidebarSheet -> LinkkiTabSheet
** getIcon() -> getTab().getChildren().findFirst().get()
** getName() -> getDescription()
** SidebarSheet(String id, VaadinIcon icon, String name, Supplier<Component> contentSupplier, Handler uiUpdateObserver) -> LinkkiTabSheet.buildWithId(id)
                .withCaption(icon.create())
                .withDescription(name)
                .withContent(contentSupplier)
                .withOnSelectHandler(uiUpdateObserver)
				
* SidebarLayout -> LinkkiTabLayout.newSidebarLayout():
** addSheets -> addTabSheets
** addSheet -> addTabSheet
** addSelectionListener -> addSelectedChangeListener
** SelectionEvent#getOldValue -> SelectedChangeEvent#getPreviousTab
** SelectionEvent#getSelectedSheet -> SelectedChangeEvent#getSelectedTab
** select(id) -> setSelectedTabSheet
** select(sheet) -> setSelectedTabSheet(sheet.getId())
** getSelected -> getSelectedTabSheet
** getSidebarSheet(id) -> getTabSheet(id)
** getSidebarSheets -> getTabSheets

* TabSheetArea -> LinkkiTabLayout (LIN-2158):
** TabSheetArea wurde entfernt, Ersatz/Neueinführung wird in LIN-2065 evaluiert
** addTab -> addTabSheet
** createContent -> Kinder müssen manuell hinzugefügt werden
** updateContent entfernt (-> LIN-2065)