:jbake-title: Data Binding with PMOs
:jbake-type: section
:jbake-status: published

:source-dir: ../../../../src/main/java
:images-folder-name: 03_architecture

[[databinding]]
=== Data Binding with PMOs

With *linkki*, UI components are defined in so called Presentation Model Objects (PMOs). The dynamic aspects of the UI are defined in methods, while the UI component itself is defined in annotations. This enables a declarative definition of UIs.

The PMO isn't required to hold all data itself. It can delegate to domain model objects (see <<domain-model-binding,Data on Multiple Layers>>) to directly make use of existing domain logic.

[[pmo]]
==== *linkki* PMO and PMO properties

In *linkki*, PMOs are Plain Old Java Objects (POJOs), in which data for individual UI layouts are structured.

Of importance for the data binding are the so called *properties* of a PMO. A PMO has a PMO property named "something" if and only if that class has a method `getSomething()` (`isSomething()` for boolean). If the value of this property is to be modifiable, the method `setSomething` must exist additionally. The value of the property may be stored in a field `something` but that is not required. Neither does a PMO have to be a JavaBean with a zero-argument constructor.

See the following example class:

[source,java]
----
include::{source-dir}/org/linkki/doc/ExamplePmo.java[tags=class]
----

This class has two properties: "salutation" and "nameForUI". The property "nameForUI" shows, that for a PMO property there doesn't necessarily have to exist a corresponding field. Also, "surname" is no property even though there is a field and a matching setter method, because the required method `String getSurname()` is missing.

[[pmo-annotation]]
==== Defining UI components in a PMO

UI components are defined by using annotations. Each PMO property can be defined as UI component by using an <<ui-element, UI element annotation>>. In addition the PMO itself can be defined as a <<layout, layout>>. 

.Example: annotated PMO
[source,java]
----
include::{source-dir}/org/linkki/doc/PartnerSectionPmo.java[tags=pmo]
----

==== Additional interfaces for PMOs

There are some optional interfaces that PMO classes may implement:

* `org.linkki.core.pmo.PresentationModelObject` offers a method for the creation of a button PMO. This button is displayed in the section header if the PMO is annotated with <<layout-section, @UISection>>.
* `org.linkki.core.pmo.ButtonPmo` is a PMO for buttons, see <<ui-button,Buttons>>
* `org.linkki.core.defaults.columnbased.pmo.ContainerPmo` is a PMO for tables, of which each row is represented by regular PMOs. See <<ui-container-pmo,Container Components>>